*&---------------------------------------------------------------------*
*& Include          SAPMZDOC_TRACKER_T01
*&---------------------------------------------------------------------*

*** Type Decleration
  TYPES :
    BEGIN OF TY_DATA,
      SLNO       TYPE INT4,
      INWARD_DOC TYPE ZINWD_DOC,
      QR_CODE    TYPE ZQR_CODE,
      STATUS     TYPE ZSTATUS,
      DES        TYPE CHAR40,
    END OF TY_DATA.

*** Data Decleration
  DATA :
    GV_DATE       TYPE SY-DATUM,
    GV_STATUS     TYPE ZSTATUS,
    GV_QR         TYPE ZQR_CODE,
    GV_DOC_STATUS TYPE ZDC_STATUS,
    GV_SENDOR     TYPE ZSENDER,
    GV_RECEIVER   TYPE ZREC,
    GV_MODE(1)    VALUE 'E'.

  DATA :
    GS_TRACKER TYPE ZDOC_T_TRACK,
    GT_TRACKER TYPE TABLE OF ZDOC_T_TRACK,
    GS_DATA    TYPE TY_DATA,
    GT_DATA    TYPE STANDARD TABLE OF TY_DATA.

*** Constants
  CONSTANTS :
    C_STATUS00(2) VALUE ' ',
    C_STATUS01(2) VALUE '01',
    C_STATUS02(2) VALUE '02',
    C_STATUS03(2) VALUE '03',
    C_STATUS04(2) VALUE '04',
    C_X(1)        VALUE 'X',
    C_BACK        TYPE SYUCOMM VALUE 'BACK',
    C_EXIT        TYPE SYUCOMM VALUE 'EXIT',
    C_CANCEL      TYPE SYUCOMM VALUE 'CANCEL',
    C_ENTER       TYPE SYUCOMM VALUE 'ENTER',
    C_SAVE        TYPE SYUCOMM VALUE 'SAVE'.

*** Custom Container
  DATA:
    CONTAINER   TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
    GRID        TYPE REF TO CL_GUI_ALV_GRID,
    GT_EXCLUDE  TYPE UI_FUNCTIONS,
    GS_LAYO     TYPE LVC_S_LAYO,
    GT_FIELDCAT TYPE LVC_T_FCAT,
    GS_FIELDCAT TYPE LVC_S_FCAT,
    OK_9001     TYPE SY-UCOMM.

*** Selection Screen
  SELECTION-SCREEN : BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.
  PARAMETERS:
    R_RB1 RADIOBUTTON GROUP G1,
    R_RB2 RADIOBUTTON GROUP G1,
    R_RB3 RADIOBUTTON GROUP G1,
    R_RB4 RADIOBUTTON GROUP G1.
  SELECTION-SCREEN END OF BLOCK B2.

  START-OF-SELECTION.
    CALL SCREEN 9001.
