*&---------------------------------------------------------------------*
*& Include          SAPMZ_TATKAL_PO_T01
*&---------------------------------------------------------------------*

TYPES :
  BEGIN OF TY_HDR,
    QR_CODE  TYPE ZQR_CODE,
    INWD_DOC TYPE ZINWD_DOC,
    MBLNR    TYPE MBLNR,
    EBELN    TYPE EBELN,
    CHARG    TYPE CHARG_D,
    LIFNR    TYPE LIFNR,
    NAME1    TYPE NAME1_GP,
  END OF TY_HDR,

  BEGIN OF TY_ITEM,
    EBELP    TYPE EBELP,
    MATNR    TYPE MATNR,
    CHARG    TYPE CHARG_D,
    MENGE    TYPE MENGE_D,
    MENGE_S  TYPE MENGE_D,
    MEINS    TYPE LAGME,
    NETPR    TYPE BPREI,
    WAERS    TYPE WAERS,
    NETWR    TYPE BWERT,
    BPREI_GP TYPE BPREI,
    BPREI_T  TYPE BPREI,
    LGORT    TYPE LGORT_D,
    WERKS    TYPE WERKS_D,
    MWSKZ    TYPE MWSKZ,
  END OF TY_ITEM.

*** Internal Tables
DATA :
  GS_HDR     TYPE TY_HDR,
  GT_ITEM    TYPE STANDARD TABLE OF TY_ITEM,
  GT_ITEM_T  TYPE STANDARD TABLE OF TY_ITEM,
  GS_INW_HDR TYPE ZINW_T_HDR.

DATA :
  CONTAINER        TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
  GRID             TYPE REF TO CL_GUI_ALV_GRID,
  MYCONTAINER      TYPE SCRFNAME VALUE 'MYCONTAINER',
  GT_EXCLUDE       TYPE UI_FUNCTIONS,
  GS_LAYO          TYPE LVC_S_LAYO,
  GT_FIELDCAT      TYPE LVC_T_FCAT,
  OK_9000          TYPE SY-UCOMM,
  OK_9001          TYPE SY-UCOMM,
  GV_MBLNR_103     TYPE MBLNR,
  GV_SUBRC         TYPE SY-SUBRC,
  GV_CUR_FIELD(10),
  GV_CUR_VALUE(10),
  GV_EBELN         TYPE EBELN,
  GV_MOD(1)        VALUE 'E',
  GV_PO_CREATE(1),
  GV_GOODS_MVT(1),
  GV_D_NOTE(1),
  GV_VBELN         TYPE VBELN_VL,
  GV_MBLNR_N       TYPE MBLNR.

CONSTANTS :
  C_SAVE         TYPE SYUCOMM VALUE 'SAVE',
  C_ENTER        TYPE SYUCOMM VALUE 'ENTER',
  C_SPACE        TYPE SYUCOMM VALUE SPACE,
  C_BACK         TYPE SYUCOMM VALUE 'BACK',
  C_EXIT         TYPE SYUCOMM VALUE 'EXIT',
  C_CANCEL       TYPE SYUCOMM VALUE 'CANCEL',
  C_REFRESH      TYPE SYUCOMM VALUE 'REF',
  C_X(1)         VALUE 'X',
  C_E(1)         VALUE 'E',
  C_MVT_IND_B(1) VALUE 'B',
  C_MVT_01(2)    VALUE '01',
  C_101(3)       VALUE '101',
  C_02(2)        VALUE '02',
  C_03(2)        VALUE '03',
  C_04(2)        VALUE '04',
  C_D(2)         VALUE 'D',    " Display
  C_SE_CODE(20)  VALUE 'SOE',
  C_SE03(4)      VALUE 'SE03',
  C_SE04(4)      VALUE 'SE04',
  C_161(3)       VALUE '161'.

*** PO Creation Data
DATA:
  HEADER      LIKE BAPIMEPOHEADER,
  HEADERX     LIKE BAPIMEPOHEADERX,
  ITEM        TYPE TABLE OF BAPIMEPOITEM  WITH HEADER LINE,
  POSCHEDULE  TYPE TABLE OF BAPIMEPOSCHEDULE WITH HEADER LINE,
  POSCHEDULEX TYPE TABLE OF BAPIMEPOSCHEDULX WITH HEADER LINE,
  ITEMX       TYPE TABLE OF BAPIMEPOITEMX  WITH HEADER LINE,
  RETURN      TYPE TABLE OF BAPIRET2.
