*&---------------------------------------------------------------------*
*& Include          SAPMZ_TRASPORTER_DET_TOP_TEST
*&---------------------------------------------------------------------*
PROGRAM SAPMZ_TRASPORTER_DET_TEST.
DATA: OK_CODE LIKE SY-UCOMM.
TYPES : BEGIN OF TY_ZINW_T_HDR,
          QR_CODE    TYPE ZQR_CODE,
          EBELN      TYPE EBELN,
          LIFNR      TYPE ELIFN,
          SERVICE_PO TYPE EBELN,
          MBLNR      TYPE MBLNR,
          LR_NO      TYPE ZLR,
          STATUS     TYPE ZSTATUS,
        END OF TY_ZINW_T_HDR.
TYPES : BEGIN OF TY_EKBE,
          EBELN TYPE EBELN,
          EBELP TYPE EBELP,
          BELNR TYPE MBLNR,
          DMBTR TYPE DMBTR_CS,
          MENGE TYPE MENGE_D,
          BEWTP TYPE BEWTP,
        END OF TY_EKBE.

TYPES : BEGIN OF TY_EKPO,
          EBELN TYPE EBELN,
          EBELP TYPE EBELP,
          MENGE TYPE BSTMG,
          NETWR TYPE BWERT,
          MWSKZ TYPE MWSKZ,
        END OF TY_EKPO.

TYPES : BEGIN OF TY_FINAL ,
          SERVICE_PO TYPE EBELN,
          AMOUNT     TYPE DMBTR_CS,
          LR_NO      TYPE ZLR,
          QR_CODE    TYPE ZQR_CODE,
          BEWTP      TYPE BEWTP,
        END OF TY_FINAL.

DATA : IT_FINAL TYPE TABLE OF  TY_FINAL,
       WA_FINAL TYPE TY_FINAL.
DATA : IT_ZINW_T_HDR TYPE TABLE OF TY_ZINW_T_HDR,
       WA_ZINW_T_HDR TYPE TY_ZINW_T_HDR,
       IT_EKBE       TYPE TABLE OF TY_EKBE,
       IT_EKBE1      TYPE TABLE OF TY_EKBE,
       WA_EKBE1      TYPE TY_EKBE,
       IT_EKPO       TYPE TABLE OF TY_EKPO,
       WA_EKBE       TYPE TY_EKBE,
       WA_EKPO       TYPE TY_EKPO.
DATA : LV_QR       TYPE ZINW_T_HDR-QR_CODE,
       QR_CODE     TYPE ZINW_T_HDR-QR_CODE,
       LV_LIFNR    TYPE LIFNR,
       LV_NAME     TYPE LFA1-NAME1,
       LV_BILL(16) TYPE C.
DATA : LV_INVOICE_NO TYPE BELNR_D.
DATA:CONTAINER   TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
     GRID        TYPE REF TO CL_GUI_ALV_GRID,
     IT_EXCLUDE  TYPE UI_FUNCTIONS,
     LW_LAYO     TYPE LVC_S_LAYO,
     LT_FIELDCAT TYPE  LVC_T_FCAT.
DATA: LT_EXCLUDE TYPE UI_FUNCTIONS.
DATA : LS_STABLE TYPE LVC_S_STBL.
DATA : LV_AMT     TYPE DMBTR_CS.

***********FOR PAYMENT
DATA :
  GT_HDR TYPE TABLE OF ZINW_T_HDR,
  GS_HDR TYPE ZINW_T_HDR.
DATA : IT_BKPF    TYPE TABLE OF BKPF,
       WA_BKPF    TYPE BKPF,
       IT_BSEG    TYPE TABLE OF BSEG,
       WA_BSEG    TYPE BSEG,
       WA_RBKP_DB TYPE RBKP,
       WA_RBKP_IV TYPE RBKP,
       LS_EKBE    TYPE EKBE,
       WA_BSIK    TYPE BSIK.

DATA : LV_AMOUNT TYPE BSIK-WRBTR .
TYPES:BEGIN OF TY_ALV,
        SNO       TYPE I,
        BUKRS     TYPE BUKRS,
        GJAHR     TYPE GJAHR,
        LIFNR     TYPE LFA1-LIFNR,
        NAME1     TYPE ADRC-NAME1,
        WRBTR     TYPE BSIK-WRBTR,
        C_BELNR   TYPE BSID-BELNR,
        C_AUGBL   TYPE BSAD-AUGBL,
        C_MESSAGE TYPE CHAR100,
        V_BELNR   TYPE BSIK-BELNR,
        V_AUGBL   TYPE BSAK-AUGBL,
        V_MESSAGE TYPE CHAR100,
*  c_type    TYPE c,
      END OF TY_ALV.
DATA : GT_ALV TYPE TABLE OF TY_ALV,
       LS_ALV TYPE TY_ALV.
DATA :  LV_PAYMENT TYPE CHAR50.
*** Constants
CONSTANTS :
  C_RFBU       TYPE GLVOR VALUE 'RFBU',
  C_KZ         TYPE BLART VALUE 'KZ',
  C_COMP_CODE  TYPE CHAR4 VALUE '1000',
  C_X(1)       VALUE 'X',
  C_E(1)       VALUE 'E',
  C_QR_CODE(7) VALUE 'QR_CODE',
  C_QR07(7)    VALUE 'QR07',
  C_01(2)      VALUE '01',
  C_02(2)      VALUE '02',
  C_03(2)      VALUE '03',
  C_04(2)      VALUE '04',
  C_05(2)      VALUE '05',
  C_06(2)      VALUE '06',
  C_07(2)      VALUE '07',
  C_GL         TYPE HKONT VALUE '0000140001'.
