*&---------------------------------------------------------------------*
*& Include          SAPMZGR_101_EVENT
*&---------------------------------------------------------------------*


*&---------------------------------------------------------------------*
*& Include          SAPMZZGRGI_EVNT
*&---------------------------------------------------------------------*

CLASS CL_EVENT_PP DEFINITION DEFERRED.
CLASS CL_EVENT_PP1 DEFINITION DEFERRED.
DATA: G_VERIFIER  TYPE REF TO CL_EVENT_PP1.
DATA: G_VERIFIER1 TYPE REF TO CL_EVENT_PP.

CLASS CL_EVENT_PP DEFINITION.

  PUBLIC SECTION.
    DATA: ERROR_IN_DATA TYPE C.

*    METHODS: UPDATE FOR EVENT DATA_CHANGED OF CL_GUI_ALV_GRID IMPORTING ER_DATA_CHANGED.
*    METHODS: TOOLBAR FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID IMPORTING E_OBJECT E_INTERACTIVE.
    METHODS: USER_COMMAND FOR EVENT AFTER_USER_COMMAND OF CL_GUI_ALV_GRID IMPORTING E_UCOMM.
    METHODS: TOOLBAR1 FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID IMPORTING E_OBJECT E_INTERACTIVE.


ENDCLASS.

CLASS CL_EVENT_PP1 DEFINITION.

  PUBLIC SECTION.

    METHODS: USER_COMMAND1 FOR EVENT AFTER_USER_COMMAND OF CL_GUI_ALV_GRID IMPORTING E_UCOMM.
    METHODS: TOOLBAR FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID IMPORTING E_OBJECT E_INTERACTIVE.

ENDCLASS.

CLASS CL_EVENT_PP IMPLEMENTATION.

  METHOD TOOLBAR1.

    DATA : MT_TOOLBAR TYPE STB_BUTTON.
    CLEAR MT_TOOLBAR.
    MT_TOOLBAR-BUTN_TYPE = 0.
    MT_TOOLBAR-FUNCTION = 'SAVE'.
    MT_TOOLBAR-ICON = '@SAVE@'.
    MT_TOOLBAR-TEXT = 'SAVE'.
    MT_TOOLBAR-QUICKINFO = 'SAVE'.
    APPEND MT_TOOLBAR TO E_OBJECT->MT_TOOLBAR.

  ENDMETHOD.

  METHOD USER_COMMAND.

    DATA: V_OK TYPE C.
    CASE E_UCOMM.
      WHEN 'SAVE'.
        PERFORM SAVE.
      WHEN OTHERS.
    ENDCASE.

  ENDMETHOD.

ENDCLASS.

CLASS CL_EVENT_PP1 IMPLEMENTATION.

  METHOD TOOLBAR.

    DATA : MT_TOOLBAR1 TYPE STB_BUTTON.
    CLEAR MT_TOOLBAR1.
    MT_TOOLBAR1-BUTN_TYPE = 0.
    MT_TOOLBAR1-FUNCTION = 'PRINT'.
    MT_TOOLBAR1-ICON = '@PRINT@'.
    MT_TOOLBAR1-TEXT = 'Print'.
    MT_TOOLBAR1-QUICKINFO = 'print'.
    APPEND MT_TOOLBAR1 TO E_OBJECT->MT_TOOLBAR.

  ENDMETHOD.

  METHOD USER_COMMAND1.

    DATA: V_OK1 TYPE C.
    CASE E_UCOMM.
      WHEN 'PRINT'.
        PERFORM PRINT.
      WHEN OTHERS.
    ENDCASE.

  ENDMETHOD.

  ENDCLASS.
