class ZCL_ZGW_HIERARCHY_DPC_EXT definition
  public
  inheriting from ZCL_ZGW_HIERARCHY_DPC
  create public .

public section.
protected section.

  methods HIERARCHY_TYPESE_GET_ENTITYSET
    redefinition .
  methods HIERARCHY_TYPESE_GET_ENTITY
    redefinition .
private section.
ENDCLASS.



CLASS ZCL_ZGW_HIERARCHY_DPC_EXT IMPLEMENTATION.


  method HIERARCHY_TYPESE_GET_ENTITY.
**TRY.
*CALL METHOD SUPER->HIERARCHY_TYPESE_GET_ENTITY
*  EXPORTING
*    IV_ENTITY_NAME          =
*    IV_ENTITY_SET_NAME      =
*    IV_SOURCE_NAME          =
*    IT_KEY_TAB              =
**    IO_REQUEST_OBJECT       =
**    IO_TECH_REQUEST_CONTEXT =
*    IT_NAVIGATION_PATH      =
**  IMPORTING
**    ER_ENTITY               =
**    ES_RESPONSE_CONTEXT     =
*    .
** CATCH /IWBEP/CX_MGW_BUSI_EXCEPTION .
** CATCH /IWBEP/CX_MGW_TECH_EXCEPTION .
**ENDTRY.
    BREAK samburi.
  endmethod.


  METHOD HIERARCHY_TYPESE_GET_ENTITYSET.
    BREAK SAMBURI.
*    FIELD-SYMBOLS : <LS_FILTER> TYPE /IWBEP/S_MGW_SELECT_OPTION.
*    DATA: GT_FILTER TYPE /IWBEP/S_MGW_SELECT_OPTION-SELECT_OPTIONS.

*    DATA: LS_KEY_TAB TYPE /IWBEP/S_MGW_NAME_VALUE_PAIR,
*          LV_USER    TYPE SY-UNAME.
*
**** Get the key property values
*    READ TABLE IT_KEY_TAB WITH KEY NAME = 'User' INTO LS_KEY_TAB.
*    IF SY-SUBRC = 0.
*      LV_USER = LS_KEY_TAB-VALUE.
*    ENDIF.
***  Get Merchandise Hierarchy with Description
    SELECT KLAH~CLASS SWOR~KSCHL FROM KLAH AS KLAH INNER JOIN SWOR AS SWOR ON SWOR~CLINT = KLAH~CLINT
           INTO CORRESPONDING FIELDS OF TABLE ET_ENTITYSET WHERE KLAH~KLART = '026' AND KLAH~WWSKZ = '0' AND SWOR~SPRAS = SY-LANGU AND SWOR~KLPOS = '1'.
    LOOP AT ET_ENTITYSET ASSIGNING FIELD-SYMBOL(<LS_SET>).
      IF <LS_SET>-KSCHL CA '*'.
        <LS_SET>-USER = 'X'.  " Delection Flag
      ELSE.
        <LS_SET>-USER = SY-UNAME.
      ENDIF.
    ENDLOOP.
    DELETE ET_ENTITYSET WHERE USER = 'X'.
    SORT ET_ENTITYSET BY CLASS.
    DELETE ADJACENT DUPLICATES FROM ET_ENTITYSET.
  ENDMETHOD.
ENDCLASS.
