*
*   INCLUDE LCLFMF87
*
*   OK-CODE subroutines:  ok_*
*
*   Called via DB table TCLOKCODE.
**********************************************************************

  INCLUDE LCLFMF5W .  " OK_ABBR

  INCLUDE LCLFMF5V .  " OK_AEBL

  INCLUDE LCLFMF5U .  " OK_AEDA

  INCLUDE LCLFMF5T .  " OK_AEDI

  INCLUDE LCLFMF5S .  " OK_AL_SIZE

  INCLUDE LCLFMF5R .  " OK_AL_STEP

  INCLUDE LCLFMF5Q .  " OK_AUSW

  INCLUDE LCLFMF5P .  " OK_BLOC

  INCLUDE LCLFMF5O .  " OK_CLFM_CHNG

  INCLUDE LCLFMF5N .  " OK_CLFM_DISP

  INCLUDE LCLFMF5M .  " OK_CLS_STACK

  INCLUDE LCLFMF5L .  " OK_EINT

  INCLUDE LCLFMF5K .  " OK_ENDE

  INCLUDE LCLFMF5J .  " OK_ENTE

  INCLUDE LCLFMF5I .  " OK_F21
  INCLUDE LCLFMF5H .  " OK_F22
  INCLUDE LCLFMF5G .  " OK_F23
  INCLUDE LCLFMF5F .  " OK_F24

  INCLUDE LCLFMF5E .  " OK_FILT

  INCLUDE LCLFMF5D .  " OK_FIXI

  INCLUDE LCLFMF5C .  " OK_HCLA

  INCLUDE LCLFMF5B .  " OK_HCLG

  INCLUDE LCLFMF5A .  " OK_INKONSI

  INCLUDE LCLFMF59 .  " OK_LOES

  INCLUDE LCLFMF58 .  " OK_MADE

  INCLUDE LCLFMF57 .  " OK_MALL

  INCLUDE LCLFMF56 .  " OK_MARK

  INCLUDE LCLFMF55 .  " OK_MEIN

  INCLUDE LCLFMF54 .  " OK_NEUZ

  INCLUDE LCLFMF53 .  " OK_NEZU

  INCLUDE LCLFMF52 .  " OK_OBJ_DISP

  INCLUDE LCLFMF51 .  " OK_OBJA

  INCLUDE LCLFMF4Z .  " OK_OBWE

  INCLUDE LCLFMF4Y .  " OK_PARA

  INCLUDE LCLFMF4X .  " OK_PICK

  INCLUDE LCLFMF4W .  " OK_RELE

  INCLUDE LCLFMF4V .  " OK_SAVE

  INCLUDE LCLFMF4T .  " OK_SPAR

  INCLUDE LCLFMF4S .  " OK_STAT

  INCLUDE LCLFMF4R .  " OK_STCL

  INCLUDE LCLFMF4Q .  " OK_TRCE

  INCLUDE LCLFMF4P .  " OK_UCLA

  INCLUDE LCLFMF4O .  " OK_UCLG

  INCLUDE LCLFMF4N .  " OK_UEBN

  INCLUDE LCLFMF4M .  " OK_UEB_BILD

  INCLUDE LCLFMF4L .  " OK_USER_PARM

  INCLUDE LCLFMF4K .  " OK_VIEW

  INCLUDE LCLFMF4J .  " OK_WECH

  INCLUDE LCLFMF4I .  " OK_WEIT

  INCLUDE LCLFMF4H .  " OK_XCLA

  INCLUDE LCLFMF4G .  " OK_XCLG

  INCLUDE LCLFMF6A .  " OK_TYP_CHG
