* include LCLFMF50
* Clfy 99: different forms.

************************************************************************

  INCLUDE LCLFMF3H .  " AUTHORITY_CHECK_CLASSIFY

  INCLUDE LCLFMF3G .  " CHECK_ALL_CHANGES

  INCLUDE LCLFMF3F .  " GET_OBJECT_CUST_DATA

  INCLUDE LCLFMF3E .  " READ_SELECTED_LINE

  INCLUDE LCLFMF3D .  " LEAVE_CLFY

  INCLUDE LCLFMF3C .  " LOESCHEN_MARK

  INCLUDE LCLFMF3B .  " REBUILD_OBJI

  INCLUDE LCLFMF3A .  " RECOVER_KLASTAB

  INCLUDE LCLFMF39 .  " SELECT_ALLOC_OBJTYPE

  INCLUDE LCLFMF38 .  " SETUP_KLASTAB_INDEX

  INCLUDE LCLFMF37 .  " SETUP_TABLE_REDUN

  INCLUDE LCLFMF36 .  " SETUP_TABLE_TABAUSW


