  INCLUDE ZLCLFMF2N .  " LESEN_KSSK

  INCLUDE LCLFMF2M .  " LESEN_KSSK_INDEX

  INCLUDE LCLFMF2L .  " AUFBAUEN_ALLKSSK_VIEW

  INCLUDE LCLFMF2K .  " BUILD_VIEWTAB

  INCLUDE LCLFMF2J .  " AUSWAHL

  INCLUDE LCLFMF2I .  " KLASSIFIZIEREN

  INCLUDE LCLFMF2H .  " BUILD_ALLAUSP

  INCLUDE LCLFMF2G .  " BUILD_SICHT

  INCLUDE LCLFMF2F .  " REF_KLASSIFIZIEREN

  INCLUDE LCLFMF2E .  " POPUP_LOESCHEN

  INCLUDE LCLFMF2D .  " LOESCHEN

  INCLUDE LCLFMF2B .  " CHECK_STRUCTURE

  INCLUDE LCLFMF2A .  " CHECK_STDCL



  INCLUDE LCLFMF29 .  " DELETE_DATABASE

  INCLUDE LCLFMF28 .  " FUELLEN_DELCL

  INCLUDE LCLFMF27 .  " BUILD_ALL_TABS

  INCLUDE LCLFMF26 .  " DELETE_ALL_TABS

  INCLUDE LCLFMF25 .  " LOESCHEN_DUNKEL

  INCLUDE ZLCLFMF24 .  " INSERT_CLASSIFICATION

  INCLUDE LCLFMF23 .  " DELETE_CLASSIFICATION

  INCLUDE LCLFMF22 .  " DELETE_OBJ_CLASSIFICATION

  INCLUDE LCLFMF21 .  " RENAME_CLASSIFICATION

  INCLUDE LCLFMF1Z .  " SPERREN_KLAS

  INCLUDE LCLFMF1Y .  " ENTSPERREN_KLAS

  INCLUDE LCLFMF1X .  " SPERREN_KSSKS

  INCLUDE LCLFMF1W .  " ENTSPERREN_KSSKS

  INCLUDE LCLFMF1V .  " SPERREN_KSSKX

  INCLUDE LCLFMF1U .  " SPERREN_KSSKKS

  INCLUDE LCLFMF1T .  " ENTSPERREN_KSSKKS

  INCLUDE LCLFMF1S .  " BEENDEN

  INCLUDE LCLFMF1R .  " BEENDEN_OHNE

  INCLUDE LCLFMF1Q .  " BEENDEN_TAB_LOESCH

  INCLUDE LCLFMF1P .  " SORT_SAVE

  INCLUDE LCLFMF1O .  " BLAETTERN

  INCLUDE LCLFMF1N .  " OHNE_BEWERTUNG


  INCLUDE LCLFMF1M .  " STATUS_CHECK

  INCLUDE LCLFMF1K .  " REKURSION_PRUEFEN

  INCLUDE LCLFMF1J .  " REK_STUECKLISTE

  INCLUDE LCLFMF1I .  " UNIT_CHECK

  INCLUDE LCLFMF1G .  " CHK_BATCH

  INCLUDE LCLFMF1F .  " ALLAUSP_NEW
  INCLUDE LCLFMF1E .  " ALLAUSP_NEW_FILL
