  INCLUDE LCLFMF35 .  " SHOW_ALL_KSSK_FROM_OBJECT

  INCLUDE LCLFMF34 .  " CHECK_AENNRF

  INCLUDE LCLFMF33 .  " CHECK_AENNRF_SEL

  INCLUDE LCLFMF32 .  " SEND_CHANGE_DYNPRO

  INCLUDE LCLFMF31 .  " CHECK_KSSK_COUNT

  INCLUDE LCLFMF2Y .  " CREATE_ICON

  INCLUDE LCLFMF2X .  " RESET_CLASS

  INCLUDE LCLFMF2W .  " LESEN_UDEF


  INCLUDE LCLFMF2V .  " BUILD_CHARS
