  INCLUDE LCLFMO0F .  " SET_PFSTATUS

  INCLUDE LCLFMO0E .  " SET_CURSOR

  INCLUDE LCLFMO0D .  " SORT_KLASTAB

  INCLUDE LCLFMO0C .  " NEUE_EINTRAEGE

  INCLUDE LCLFMO0B .  " PAGPOS_OUT

  INCLUDE LCLFMO0A .  " DRUCKTASTE

  INCLUDE LCLFMO09 .  " LIST_ITCLC

  INCLUDE LCLFMO08 .  " SUPPRESS_DIALOG

  INCLUDE LCLFMO07 .  " INIT_D602

  INCLUDE LCLFMO06 .  " LIST_IATINN

  INCLUDE LCLFMO05 .  " LIST_D604

  INCLUDE LCLFMO04 .  " REBUILD_OBJ_INDX

  INCLUDE LCLFMO03 .  " MODIFY_SCREEN


  INCLUDE LCLFMO02 .  " MODIFY_SCREEN_600


  INCLUDE LCLFMF5X .  " SET_EFFE_ICON
