*-------------------------------------------------------------------
***INCLUDE LCLFMF70 .
*-------------------------------------------------------------------

  INCLUDE LCLFMF3Z .  " RMCLF-ATWRT_F4
  INCLUDE LCLFMF3Y .  " STATUS_CHK_INSERT
  INCLUDE LCLFMF3X .  " CUST_EXIT_POST
  INCLUDE LCLFMF3W .  " KSSK_FREIGABE
  INCLUDE LCLFMF3V .  " RELEASE_MARKED
  INCLUDE LCLFMF3U .  " RMCLF_ABTEI_CHK
  INCLUDE LCLFMF3T .  " RMCLF_ABTEI_F4
  INCLUDE LCLFMF3S .  " RMCLF_ABTEI_SAVE

  INCLUDE LCLFMF3R .  " GET_SELECTED_CLASS
  INCLUDE LCLFMF3Q .  " LESEN_TCLC

  INCLUDE LCLFMF3P .  " DELETE_DELCL

  INCLUDE LCLFMF3O .  " MODIFY_SCREEN_600

  INCLUDE LCLFMF3N .  " MODIFY_SCREEN
