  INCLUDE LCLFMI0J .  " OK_BEENDEN

  INCLUDE LCLFMI0I .  " OK_BEENDEN_WIN
  INCLUDE LCLFMI0H .  " OK_CODE

  INCLUDE LCLFMI0G .  " OK_CODE2

  INCLUDE LCLFMI0F .  " REFRESH_KLASTAB

  INCLUDE LCLFMI0E .  " FUELLEN_TAB

  INCLUDE LCLFMI0D .  " CHECK_STATUS

  INCLUDE LCLFMI0C .  " MODIFY_TAB

  INCLUDE LCLFMI0A .  " MMARKIEREN

  INCLUDE LCLFMI09 .  " LOOPZIEHEN


  INCLUDE LCLFMI08 .  " SEITE

  INCLUDE LCLFMI07 .  " SEITE_REQ

  INCLUDE LCLFMI06 .  " SETZEN_KREUZ

  INCLUDE LCLFMI05 .  " GET_CURSOR

  INCLUDE LCLFMI04 .  " SETZEN_KREUZ_D604

  INCLUDE LCLFMI03 .  " CHECK_AENNR

  INCLUDE LCLFMI02 .  " MODIFY_ZAEHL

  INCLUDE LCLFMI0K .  " HELP_TEXT
