*&---------------------------------------------------------------------*
*& Report ZTEST_SE
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZENTRYSHEET_CREATE.

DATA:
  BAPI_ESLL        LIKE BAPIESLLC OCCURS 1 WITH HEADER LINE,
  PO_ITEMS         TYPE BAPIEKPO OCCURS 0 WITH HEADER LINE,
  PO_SERVICES      TYPE BAPIESLL OCCURS 0 WITH HEADER LINE,
  BAPI_RETURN_PO   TYPE TABLE OF BAPIRET2,
  WA_HEADER        TYPE BAPIESSRC,
  I_RETURN         TYPE TABLE OF BAPIRET2,
  SERIAL_NO        LIKE BAPIESKNC-SERIAL_NO,
  LINE_NO          LIKE BAPIESLLC-LINE_NO,
  WS_ENTRYSHEET_NO TYPE  BAPIESSR-SHEET_NO.

DATA:
  BEGIN OF WA_PO_HEADER OCCURS 1.
    INCLUDE STRUCTURE BAPIEKKOL.
  DATA: END OF WA_PO_HEADER.

PARAMETERS : P_PO TYPE EBELN.
CALL FUNCTION 'BAPI_PO_GETDETAIL'
  EXPORTING
    PURCHASEORDER    = P_PO
    ITEMS            = 'X'
    SERVICES         = 'X'
  IMPORTING
    PO_HEADER        = WA_PO_HEADER
  TABLES
    PO_ITEMS         = PO_ITEMS
    PO_ITEM_SERVICES = PO_SERVICES
    RETURN           = BAPI_RETURN_PO.

WA_HEADER-PO_NUMBER = PO_ITEMS-PO_NUMBER.
WA_HEADER-PO_ITEM = PO_ITEMS-PO_ITEM.
WA_HEADER-SHORT_TEXT = 'Service Entry Sheet'.
WA_HEADER-ACCEPTANCE = 'X'.
WA_HEADER-POST_DATE = SY-DATUM.
WA_HEADER-DOC_DATE = SY-DATUM.
WA_HEADER-PCKG_NO = 1.
SERIAL_NO = 0.
LINE_NO = 1.

BAPI_ESLL-PCKG_NO = 1.
BAPI_ESLL-LINE_NO = LINE_NO.
BAPI_ESLL-OUTL_LEVEL = '0'.
BAPI_ESLL-OUTL_IND = 'X'.
BAPI_ESLL-SUBPCKG_NO = 2.
APPEND BAPI_ESLL.

LOOP AT PO_SERVICES WHERE NOT SHORT_TEXT IS INITIAL.
  CLEAR BAPI_ESLL.
  BAPI_ESLL-PCKG_NO = 2.
  BAPI_ESLL-LINE_NO = LINE_NO * 10.
  BAPI_ESLL-SERVICE = PO_SERVICES-SERVICE.
  BAPI_ESLL-SHORT_TEXT = PO_SERVICES-SHORT_TEXT.
  BAPI_ESLL-QUANTITY = PO_SERVICES-QUANTITY.
  BAPI_ESLL-GR_PRICE = PO_SERVICES-GR_PRICE.
  BAPI_ESLL-PRICE_UNIT = PO_SERVICES-PRICE_UNIT.
  APPEND BAPI_ESLL.
  LINE_NO = LINE_NO + 1.
ENDLOOP.


CALL FUNCTION 'BAPI_ENTRYSHEET_CREATE'
  EXPORTING
    ENTRYSHEETHEADER   = WA_HEADER
  IMPORTING
    ENTRYSHEET         = WS_ENTRYSHEET_NO
  TABLES
    ENTRYSHEETSERVICES = BAPI_ESLL
    RETURN             = I_RETURN.

DATA(WS_WAIT) = '3'.
CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'
  EXPORTING
    WAIT = WS_WAIT.
