*&---------------------------------------------------------------------*
*& Include          ZFI_ACCOUNTANT_DIARY_SEL
*&---------------------------------------------------------------------*

SELECTION-SCREEN : BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
*PARAMETERS  : S_DATE type SY-DATUM.
PARAMETERS  : S_DATE TYPE C AS LISTBOX VISIBLE LENGTH 20 ."type SY-DATUM.
SELECTION-SCREEN : END OF BLOCK B1.

TYPE-POOLS: VRM. " Use type group VRM for list

INITIALIZATION. "initialize values to drop down list
  WA_LIST-KEY = '01'.
  WA_LIST-TEXT = 'Jan'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '02'.
  WA_LIST-TEXT = 'Feb'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '03'.
  WA_LIST-TEXT = 'Mar'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '04'.
  WA_LIST-TEXT = 'Apr'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '05'.
  WA_LIST-TEXT = 'May'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '06'.
  WA_LIST-TEXT = 'Jun'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '07'.
  WA_LIST-TEXT = 'Jul'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '08'.
  WA_LIST-TEXT = 'Aug'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '09'.
  WA_LIST-TEXT = 'Sep'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '10'.
  WA_LIST-TEXT = 'Oct'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '11'.
  WA_LIST-TEXT = 'Nov'.
  APPEND WA_LIST TO IT_LIST.
  WA_LIST-KEY = '12'.
  WA_LIST-TEXT = 'Dec'.
  APPEND WA_LIST TO IT_LIST.

  SORT IT_LIST ASCENDING BY KEY  .

  CALL FUNCTION 'VRM_SET_VALUES'
    EXPORTING
      ID              = 'S_DATE'
      VALUES          = IT_LIST
    EXCEPTIONS
      ID_ILLEGAL_NAME = 1
      OTHERS          = 2.


AT SELECTION-SCREEN ON S_DATE.
  BREAK breddy .
  CLEAR: WA_VALUES, IT_VALUES.
  REFRESH IT_VALUES.
  WA_VALUES-FIELDNAME = 'S_DATE'.
  APPEND WA_VALUES TO IT_VALUES.
  CALL FUNCTION 'DYNP_VALUES_READ'
    EXPORTING
      DYNAME             = SY-CPROG
      DYNUMB             = SY-DYNNR
      TRANSLATE_TO_UPPER = 'X'
    TABLES
      DYNPFIELDS         = IT_VALUES.

  READ TABLE IT_VALUES INDEX 1 INTO WA_VALUES.
  IF SY-SUBRC = 0 AND WA_VALUES-FIELDVALUE IS NOT INITIAL.
    READ TABLE IT_LIST INTO WA_LIST
                      WITH KEY KEY = WA_VALUES-FIELDVALUE.
    IF SY-SUBRC = 0.
      CONCATENATE '01' WA_LIST-KEY SY-DATUM+0(4) INTO LV_SDATE .
      CALL FUNCTION 'HR_E_NUM_OF_DAYS_OF_MONTH'
        EXPORTING
          P_FECHA        = LV_SDATE
        IMPORTING
          NUMBER_OF_DAYS = LV_DAYS.


      CALL FUNCTION 'FIAPPL_ADD_DAYS_TO_DATE'
        EXPORTING
          I_DATE      = S_DATE
          I_DAYS      = 30
          SIGNUM      = '+'
        IMPORTING
          E_CALC_DATE = LV_EDATE.

*      LV_DAY =    LV_DAYS - S_DATE+6(2) .
    ENDIF.
  ENDIF.
