*&---------------------------------------------------------------------*
*& Include          ZFI_ACCOUNTANT_DIARY_TOP
*&---------------------------------------------------------------------*
DATA : DO_SUM TYPE C.
*TYPES : BEGIN OF TY_EKKO,
*          EBELN TYPE EBELN,
*          AEDAT TYPE AEDAT,
*        END OF TY_EKKO,
*
*        BEGIN OF TY_ZINW_T_HDR,
*          QR_CODE   TYPE ZQR_CODE,
*          EBELN     TYPE EBELN,
*          LIFNR     TYPE ELIFN,
*          NAME1     TYPE NAME1_GP,
**          GPRO_STATUS TYPE ZGPRS,
*          STATUS    TYPE ZSTATUS,
*          MBLNR_103 TYPE MBLNR,
*          MBLNR     TYPE MBLNR,
**          MENGE_P      TYPE ZMENGE_P,
*          GRPO_NO   TYPE ZGRPO_NO,
**          GRPO_DATE  TYPE ZGRPO_DATE,
*          GPRO_DATE TYPE ZDAT,
*        END OF TY_ZINW_T_HDR,
*
*        BEGIN OF TY_ZINW_T_ITEM,
*          QR_CODE  TYPE ZQR_CODE,
*          EBELN    TYPE EBELN,
*          EBELP     TYPE EBELP,
*          MATNR     TYPE MATNR,
*          MATKL    TYPE MATKL,
*          NETPR_P  TYPE ZBPREI_P,
*          NETPR_GP TYPE ZBPREI_GP,
*          MENGE_P  TYPE ZMENGE_P,
*        END OF TY_ZINW_T_ITEM,
*
*        BEGIN OF TY_EKBE,
*          EBELN TYPE EBELN,
*          EBELP  TYPE EBELP,
*          ZEKKN  TYPE DZEKKN,
*          VGABE  TYPE VGABE,
*          BEWTP TYPE BEWTP,
*        END OF TY_EKBE,
*
*        BEGIN OF TY_EKPO,
*          EBELN TYPE  EBELN,
*          EBELP TYPE EBELP,
*          REPOS TYPE REPOS,
*        END OF TY_EKPO.
*
*DATA : IT_EKKO        TYPE TABLE OF TY_EKKO,
*       WA_EKKO        TYPE TY_EKKO,
*       IT_ZINW_T_HDR  TYPE TABLE OF TY_ZINW_T_HDR,
*       IT_EKPO        TYPE TABLE OF TY_EKPO,
*       WA_EKPO        TYPE  TY_EKPO,
*       IT_ZINW_T_ITEM TYPE TABLE OF TY_ZINW_T_ITEM,
*       IT_EKBE        TYPE TABLE OF TY_EKBE,
*       WA_ZINW_T_HDR  TYPE TY_ZINW_T_HDR,
*       WA_EKBE        TYPE TY_EKBE,
*       WA_ZINW_T_ITEM TYPE TY_ZINW_T_ITEM.

  DATA : LV_EDATE TYPE  SY-DATUM .
  DATA : LV_SDATE TYPE  SY-DATUM .
  DATA : LV_DAYS TYPE P .
  DATA : LV_DAY(10) TYPE C .
  DATA : D(10) TYPE C .

TYPES : BEGIN OF TY_EKKO ,
          EBELN        TYPE EKKO-EBELN,
          BSART        TYPE EKKO-BSART,
          LOEKZ        TYPE EKKO-LOEKZ,
          AEDAT        TYPE EKKO-AEDAT,
          LIFNR        TYPE EKKO-LIFNR,
          WAERS        TYPE EKKO-WAERS,
          ZTERM        TYPE EKKO-ZTERM,
          ZBD1T        TYPE EKKO-ZBD1T,
          EBELP        TYPE EKPO-EBELP,
          REPOS        TYPE EKPO-REPOS,
          QR_CODE      TYPE ZINW_T_HDR-QR_CODE,
          NAME1        TYPE ZINW_T_HDR-NAME1,
          STATUS       TYPE ZINW_T_HDR-STATUS,
*             DUE_D        TYPE ZINW_T_HDR-DUE_DATE,
          SOE          TYPE ZINW_T_HDR-SOE,
          MBLNR_103    TYPE ZINW_T_HDR-MBLNR,
          MBLNR        TYPE ZINW_T_HDR-MBLNR,
*             GRPO_NO   TYPE   ZINW_T_HDR-GRPO_NO,
          CREATED_DATE TYPE ZINW_T_STATUS-CREATED_DATE,
*             GPRO_DATE TYPE   ZINW_T_HDR-GPRO_DATE,
          INWD_DOC     TYPE ZINW_T_HDR-INWD_DOC,
          REC_DATE     TYPE ZINW_T_HDR-REC_DATE,
          MATNR        TYPE ZINW_T_ITEM-MATNR,
          MATKL        TYPE ZINW_T_ITEM-MATKL,
          NETPR_P      TYPE ZINW_T_ITEM-NETPR_P,
          NETWR_P      TYPE ZINW_T_ITEM-NETWR_P,
          NETPR_GP     TYPE ZINW_T_ITEM-NETPR_GP,
          MENGE_P      TYPE ZINW_T_ITEM-MENGE_P,
          DUE_DATE     TYPE DATUM,
*             VGABE     TYPE EKBE-VGABE,
*             BEWTP     TYPE EKBE-BEWTP,
        END OF TY_EKKO .

TYPES : BEGIN OF TY_EKBE,
          EBELN TYPE EKBE-EBELN,
          EBELP TYPE EKBE-EBELP,
          ZEKKN TYPE EKBE-ZEKKN,
          VGABE TYPE EKBE-VGABE,
          GJAHR TYPE EKBE-GJAHR,
          BELNR TYPE EKBE-BELNR,
          BUZEI TYPE EKBE-BUZEI,
          BEWTP TYPE EKBE-BEWTP,
          LFBNR TYPE EKBE-LFBNR,
        END OF TY_EKBE.


TYPES : BEGIN OF TY_FINAL ,
          SLNO         TYPE I,
          DATE         TYPE SY-DATUM,
          AMOUNT       TYPE NETPR,
          CURRENCY     TYPE WAERS,
          EBELN        TYPE EKKO-EBELN,
          EBELP        TYPE EKPO-EBELP,
          WAERS        TYPE EKKO-WAERS,
          LIFNR        TYPE EKKO-LIFNR,
          NAME1        TYPE ZINW_T_HDR-NAME1,
          GRPO_NO      TYPE   ZINW_T_HDR-MBLNR,
          DUE_DATE     TYPE  SY-DATUM,
*             GPRO_DATE TYPE   ZINW_T_HDR-GPRO_DATE,
          CREATED_DATE TYPE ZINW_T_STATUS-CREATED_DATE,
          MATKL(20),"     TYPE  ZINW_T_ITEM-MATKL,
          AEDAT        TYPE EKKO-AEDAT,
          INWD_DOC     TYPE ZINW_T_HDR-INWD_DOC,
          REC_DATE     TYPE ZINW_T_HDR-REC_DATE,
        END OF TY_FINAL .

DATA : AMOUNT TYPE EKPO-NETPR .
DATA :IT_FINAL TYPE TABLE OF TY_FINAL,
      WA_FINAL TYPE TY_FINAL.

DATA : LV_S(10) TYPE I VALUE 1 .
DATA :IT_FINAL1 TYPE TABLE OF TY_FINAL,
      WA_FINAL1 TYPE TY_FINAL.
DATA :IT_FINAL2 TYPE TABLE OF TY_FINAL,
      WA_FINAL2 TYPE TY_FINAL.
DATA :IT_FINAL3 TYPE TABLE OF TY_FINAL,
      WA_FINAL3 TYPE TY_FINAL.
DATA : IT_EKBE TYPE TABLE OF TY_EKBE,
       WA_EKBE TYPE TY_EKBE.
DATA : IT_EKBE1 TYPE TABLE OF TY_EKBE,
       WA_EKBE1 TYPE TY_EKBE.
DATA : IT_EKKO TYPE TABLE OF TY_EKKO,
       WA_EKKO TYPE TY_EKKO.
DATA :IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      WA_LAYOUT   TYPE SLIS_LAYOUT_ALV.

DATA :IT_FIELDCAT1 TYPE SLIS_T_FIELDCAT_ALV,
      WA_LAYOUT1   TYPE SLIS_LAYOUT_ALV.
DATA : LV_AMOUNT TYPE NETPR .
DATA: IT_O_WGH01 TYPE TABLE OF WGH01,
      WA_O_WGH01 TYPE WGH01.
DATA: IT_LIST     TYPE VRM_VALUES.
DATA: WA_LIST    TYPE VRM_VALUE.
DATA: IT_VALUES TYPE TABLE OF DYNPREAD,
      WA_VALUES TYPE DYNPREAD.

DATA: LV_SELECTED_VALUE(10) TYPE C.
