*&---------------------------------------------------------------------*
*& Include          ZFI_PUR_REGISTER_SEL
*&---------------------------------------------------------------------*
  """"""""""""""""""""SELECTION SCREN""""""""""""""
  SELECTION-SCREEN : BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
  SKIP 1.
  SELECT-OPTIONS : S_BELNR FOR EKBE-BELNR MODIF ID MO1,
                   S_BLDAT FOR RBKP-BLDAT MODIF ID MO1, "invoice doc date
                   S_WERKS FOR EKBE-WERKS MODIF ID MO1.
  PARAMETERS : P_GJAHR TYPE EKBE-GJAHR MODIF ID MO1,  "FISCAL YEAR
               P_BUKRS TYPE RBKP-GJAHR MODIF ID MO1.

  SELECTION-SCREEN : END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK C1 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: S_BLDAT1 FOR BKPF-BLDAT MODIF ID MO2,
                  S_GSBER FOR  BSEG-GSBER MODIF ID MO2,
                  S_GJAHR FOR  BKPF-GJAHR NO INTERVALS NO-EXTENSION MODIF ID MO2.
SELECTION-SCREEN END OF BLOCK C1.

SELECTION-SCREEN BEGIN OF BLOCK D1 WITH FRAME TITLE TEXT-001.
  PARAMETERS: P_PUR RADIOBUTTON GROUP RB1 USER-COMMAND RADIO DEFAULT 'X',
              P_NEW RADIOBUTTON GROUP RB1.
SELECTION-SCREEN END OF BLOCK D1.

AT SELECTION-SCREEN OUTPUT.

LOOP AT SCREEN.
 CHECK SCREEN-GROUP1 = 'MO1' OR SCREEN-GROUP1 = 'MO2'.
 IF P_PUR = 'X'.
   IF SCREEN-GROUP1 = 'MO2'.
   SCREEN-ACTIVE = 0.
   SCREEN-INPUT = 0.
   SCREEN-REQUIRED = 1.
  MODIFY SCREEN.
  ENDIF.
 ELSE.
 IF SCREEN-GROUP1 = 'MO1'.
   SCREEN-ACTIVE = 0.
   SCREEN-INPUT = 0.
   SCREEN-REQUIRED = 1.
 MODIFY SCREEN.
 ENDIF.
 ENDIF.
ENDLOOP.
