*&---------------------------------------------------------------------*
*& Include          ZACCOUNTANT_DIARY_T01
*&---------------------------------------------------------------------*

  DATA : LV_EDATE TYPE  SY-DATUM .
  DATA : LV_SDATE TYPE  SY-DATUM .
  DATA : LV_DAYS TYPE P .
  DATA : LV_DAY(10) TYPE C .
  DATA : D(10) TYPE C .

  TYPES :
    BEGIN OF TY_DATA,
      EBELN     TYPE EKBE-EBELN,
      EBELP     TYPE EKBE-EBELP,
      BEWTP     TYPE EKBE-BEWTP,
      BWART     TYPE EKBE-BWART,
      MENGE     TYPE EKBE-MENGE,
      BELNR     TYPE EKBE-BELNR,
      GJAHR     TYPE EKBE-GJAHR,
      BUDAT     TYPE EKBE-BUDAT,
      LFBNR     TYPE EKBE-LFBNR,
      BSART     TYPE EKKO-BSART,
      LOEKZ     TYPE EKKO-LOEKZ,
      AEDAT     TYPE EKKO-AEDAT,
      LIFNR     TYPE EKKO-LIFNR,
      WAERS     TYPE EKKO-WAERS,
      ZTERM     TYPE EKKO-ZTERM,
      ZBD1T     TYPE EKKO-ZBD1T,
      QR_CODE   TYPE ZINW_T_HDR-QR_CODE,
      NAME1     TYPE ZINW_T_HDR-NAME1,
      STATUS    TYPE ZINW_T_HDR-STATUS,
      SOE       TYPE ZINW_T_HDR-SOE,
      BILL_NUM  TYPE ZINW_T_HDR-BILL_NUM,
      MBLNR_103 TYPE ZINW_T_HDR-MBLNR_103,
      MBLNR     TYPE ZINW_T_HDR-MBLNR,
      INWD_DOC  TYPE ZINW_T_HDR-INWD_DOC,
      RETURN_PO TYPE ZINW_T_HDR-RETURN_PO,
      BILL_DATE TYPE ZINW_T_HDR-BILL_DATE,
*      LR_NO     TYPE ZINW_T_HDR-LR_NO,
      MATNR     TYPE ZINW_T_ITEM-MATNR,
      MATKL     TYPE ZINW_T_ITEM-MATKL,
      NETPR_P   TYPE ZINW_T_ITEM-NETPR_P,
      NETWR_P   TYPE ZINW_T_ITEM-NETWR_P,                              ""ZINW_T_ITEM-NETPR_GP,
      NETPR_GP  TYPE ZINW_T_ITEM-NETPR_GP,
      MENGE_P   TYPE ZINW_T_ITEM-MENGE_P,
*      RPO       TYPE EKPO-EBELN,
*      RPOI      TYPE EKPO-EBELP,
*      rQTY      TYPE EKPO-MENGE,
*      rNET      TYPE EKPO-NETPR,
*      rGROSS    TYPE EKPO-NETWR,
*      MWSKZ     TYPE EKPO-MWSKZ,
      DUE_DATE  TYPE EKBE-BUDAT,
*      BELNR1    TYPE EKBE-BELNR,
    END OF TY_DATA.

  TYPES :
    BEGIN OF TY_FINAL1,
      SLNO     TYPE INT4,
      DATE     TYPE CHAR10,
      AMOUNT   TYPE NETPR,
      CURRENCY TYPE WAERS,
      MBLNR    TYPE ZINW_T_HDR-MBLNR,
    END OF TY_FINAL1 .

  TYPES :
    BEGIN OF TY_FINAL2,
      SEL(01)      ,
      SLNO         TYPE INT4,
      DATE         TYPE SY-DATUM,
      AMOUNT       TYPE NETPR,
      CURRENCY     TYPE WAERS,
      EBELN        TYPE EKKO-EBELN,
      EBELP        TYPE EKPO-EBELP,
      WAERS        TYPE EKKO-WAERS,
      LIFNR        TYPE EKKO-LIFNR,
      NAME1        TYPE LFA1-NAME1,
      BILL_NUM     TYPE ZINW_T_HDR-BILL_NUM,
      BILL_DATE    TYPE ZINW_T_HDR-BILL_DATE,
      GRPO_NO      TYPE ZINW_T_HDR-MBLNR,
      DUE_DATE     TYPE  SY-DATUM,
      CREATED_DATE TYPE SY-DATUM,
      MATKL        TYPE MATKL,
      AEDAT        TYPE EKKO-AEDAT,
      INWD_DOC     TYPE ZINW_T_HDR-INWD_DOC,
      QR_CODE      TYPE ZINW_T_HDR-QR_CODE,
      REC_DATE     TYPE ZINW_T_HDR-REC_DATE,
*      LR_NO        TYPE ZINW_T_HDR-LR_NO,
    END OF TY_FINAL2 .

*** Tables
  DATA :
    GT_DATA    TYPE STANDARD TABLE OF TY_DATA,
    GS_DATA    TYPE TY_DATA,
    GT_DATA_PO TYPE STANDARD TABLE OF TY_DATA,
    GT_FINAL1  TYPE STANDARD TABLE OF TY_FINAL1,
    GS_FINAL1  TYPE TY_FINAL1,
    GT_FINAL2  TYPE STANDARD TABLE OF TY_FINAL2,
    GS_FINAL2  TYPE TY_FINAL2.

  DATA : IT_A003 TYPE TABLE OF A003 .
  DATA : IT_EKPO TYPE TABLE OF EKPO .
  DATA : IT_KONP TYPE TABLE OF KONP .
  DATA : GT_FTABLE TYPE STANDARD TABLE OF ZCFO_FIN1,
         GS_FTABLE TYPE ZCFO_FIN1,
         IT_BKPF   TYPE TABLE OF BKPF,
         WA_BKPF   TYPE  BKPF,
         IT_BSEG   TYPE TABLE OF BSEG,
         WA_BSEG   TYPE BSEG.

  DATA :  LV_AMOUNT TYPE ZBPREI_PT.
*** Constants
  CONSTANTS :
    C_X(1) VALUE 'X'.
