*&---------------------------------------------------------------------*
*& Include          ZGOODS_REPORT_TOP
*&---------------------------------------------------------------------*



TYPES: BEGIN OF TY_MATDOC,

*INCLUDE TYPE NSDM_S_MTDCSA_GUID  ,
*  KEY1 ,
*  KEY2  ,
*  KEY3  ,
*  KEY4  ,
*  KEY5  ,
*  KEY6  ,
  BWART TYPE 	BWART ,
  MBLNR	TYPE MBLNR ,
  BUDAT TYPE BUDAT  ,
  CPUDT TYPE CPUDT  ,
  BLDAT TYPE BLDAT  ,
  SGTXT TYPE SGTXT  ,
  BKTXT TYPE BKTXT  ,
  USNAM TYPE USNAM  ,
  ZEILE TYPE MBLPO  ,
  MATBF TYPE MATBF  ,
  MENGE TYPE MENGE_D,
  MEINS TYPE MEINS  ,
  WERKS TYPE WERKS_D ,
  EBELN TYPE BSTNR ,
 LGORT_SID TYPE	NSDM_LGORT ,
 CHARG_SID TYPE	NSDM_CHARG ,
END OF TY_MATDOC .


DATA : IT_MATDOC TYPE TABLE OF TY_MATDOC ,
      WA_MATDOC TYPE TY_MATDOC .


TYPES: BEGIN OF TY_T001W ,
  WERKS TYPE WERKS_D ,
  NAME1 TYPE NAME1  ,
  END OF TY_T001W.

  DATA : IT_T001W TYPE TABLE OF TY_T001W ,
        WA_T001W TYPE TY_T001W .

  TYPES: BEGIN OF TY_EKKO ,
    EBELN TYPE 	EBELN ,
    EKGRP	TYPE BKGRP ,
    LIFNR TYPE 	ELIFN ,
    SPRAS TYPE SPRAS ,
    END OF TY_EKKO.

  DATA : IT_EKKO TYPE TABLE OF TY_EKKO,
        WA_EKKO TYPE TY_EKKO.

TYPES: BEGIN OF TY_LFA1,
  LIFNR TYPE LIFNR,
  NAME1 TYPE NAME1_GP,
  END OF TY_LFA1.

  DATA: IT_LFA1 TYPE TABLE OF TY_LFA1 ,
        WA_LFA1 TYPE TY_LFA1 .

TYPES: BEGIN OF TY_MAKT,
   MATNR TYPE MATNR    ,
   SPRAS TYPE SPRAS    ,
   MAKTX TYPE MAKTX    ,
  END OF TY_MAKT .

  DATA : IT_MAKT TYPE TABLE OF TY_MAKT,
        WA_MAKT TYPE TY_MAKT .

TYPES: BEGIN OF TY_T024,
  EKGRP TYPE EKGRP ,
 EKNAM  TYPE  EKNAM ,

  END OF TY_T024.

  DATA : IT_T024 TYPE TABLE OF TY_T024 ,
        WA_T024 TYPE TY_T024 .


   DATA : LV_MATN TYPE MBLNR,
         LV_GRN TYPE BUDAT .

  DATA:IT_HEADER TYPE TABLE OF ZGRN_GOODS_STU,
     WA_HEADER TYPE ZGRN_GOODS_STU ,
     IT_FINAL TYPE TABLE OF ZGRN_FINAL_STU ,
     WA_FINAL TYPE ZGRN_FINAL_STU .
  DATA : PAGE1 TYPE I VALUE '0',
        PAGE TYPE I .
