*&---------------------------------------------------------------------*
*& Include          ZHR_EMP_MASTER_SELECTION
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK frm1 WITH FRAME TITLE frametxt.
SELECTION-SCREEN BEGIN OF BLOCK frm2 WITH FRAME TITLE TEXT-gsl.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 01.
PARAMETERS:
  list1 LIKE rplxxxxx-list RADIOBUTTON GROUP list DEFAULT 'X'.
SELECTION-SCREEN COMMENT 03(20) TEXT-s11 FOR FIELD list1.
SELECTION-SCREEN POSITION 33.
PARAMETERS:
  list2 LIKE rplxxxxx-list RADIOBUTTON GROUP list.
SELECTION-SCREEN COMMENT 35(15) TEXT-s12 FOR FIELD list2.
SELECTION-SCREEN POSITION 58.
PARAMETERS:
  list3 LIKE rplxxxxx-list RADIOBUTTON GROUP list.
SELECTION-SCREEN COMMENT 60(15) TEXT-s13 FOR FIELD list3.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK frm2.
SELECTION-SCREEN END OF BLOCK frm1.
