REPORT ZHRC_RECURING_PAYMENTS1
       NO STANDARD PAGE HEADING LINE-SIZE 255.




TYPE-POOLS TRUXS.
DATA:  IT_TYPE  TYPE TRUXS_T_TEXT_DATA.

INCLUDE ZHRC_RECURING_PAYMENTS1_TOP.
INCLUDE ZHRC_RECURING_PAYMENTS1_SEL.
INCLUDE ZHRC_RECURING_PAYMENTS1_FORM.


AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.

  CALL FUNCTION 'F4_FILENAME'
    EXPORTING
      PROGRAM_NAME  = SYST-CPROG
      DYNPRO_NUMBER = SYST-DYNNR
      FIELD_NAME    = 'P_FILE'
    IMPORTING
      FILE_NAME     = P_FILE.

START-OF-SELECTION.
  PERFORM GET_DATA.
  PERFORM BDC_DATA.
  PERFORM FIELDCATLOG_DESIGN.
  PERFORM DISPLAY.
