*&---------------------------------------------------------------------*
*& Include          ZMATGRP_CREATE_TOP
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*

TYPES:BEGIN OF GTY_FILE,
        SNO(5),
        MATKL(40)    TYPE C,
        WGBEZ(20)    TYPE C,
        WGBEZ60(200) TYPE C,
      END OF GTY_FILE,

      BEGIN OF GTY_FILE1,
        SNO(5),
        MATKL(09)  TYPE C,
        CLASS1(18) TYPE C,
      END OF GTY_FILE1,

      BEGIN OF GTY_FILE2,
        SNO(5),
        MATKL(09)  TYPE C,
        CLASS2(18) TYPE C,
      END OF GTY_FILE2,
      GTY_T_FILE  TYPE STANDARD TABLE OF GTY_FILE,
      GTY_T_FILE1 TYPE STANDARD TABLE OF GTY_FILE1,
      GTY_T_FILE2 TYPE STANDARD TABLE OF GTY_FILE2.
*      GTY_T_FILE3 TYPE STANDARD TABLE OF GTY_FILE2,



DATA:GWA_FILE     TYPE GTY_FILE,
     GWA_FILE1    TYPE GTY_FILE1,
     GWA_FILE2    TYPE GTY_FILE2,
     GIT_FILE     TYPE GTY_T_FILE,
     GIT_FILE1    TYPE GTY_T_FILE1,
     GIT_FILE2    TYPE GTY_T_FILE2,
     GIT_FILE_I   TYPE GTY_T_FILE,
     GIT_FILE_I1  TYPE GTY_T_FILE1,
     GIT_FILE_I2  TYPE GTY_T_FILE2,
     GIT_FILE_IT  TYPE GTY_T_FILE,
     GIT_FILE_IT1 TYPE GTY_T_FILE1,
     GIT_FILE_IT2 TYPE GTY_T_FILE2.

DATA:FNAME TYPE LOCALFILE,
     ENAME TYPE CHAR4,
     CNT   TYPE I.

TYPES:BEGIN OF GTY_DISPLAY,
        SNO      TYPE I,
        MATKL    TYPE MATKL,
        WGBEZ    TYPE WGBEZ60,
        MESSAGE1 TYPE MESSAGE,
      END OF GTY_DISPLAY,

      BEGIN OF GTY_DISPLAY1,
        SNO      TYPE I,
        MATKL    TYPE MATKL,
        CLASS1   TYPE WWGHIE,
        MESSAGE1 TYPE MESSAGE,
      END OF GTY_DISPLAY1,

      BEGIN OF GTY_DISPLAY2,
        SNO      TYPE I,
        MATKL    TYPE MATKL,
        CLASS2   TYPE WBSTR,
        MESSAGE1 TYPE MESSAGE,
      END OF GTY_DISPLAY2,
      GTY_T_DISPLAY  TYPE STANDARD TABLE OF GTY_DISPLAY,
      GTY_T_DISPLAY1 TYPE STANDARD TABLE OF GTY_DISPLAY1,
      GTY_T_DISPLAY2 TYPE STANDARD TABLE OF GTY_DISPLAY2.

DATA: GWA_DISPLAY  TYPE GTY_DISPLAY,
      GWA_DISPLAY1 TYPE GTY_DISPLAY1,
      GWA_DISPLAY2 TYPE GTY_DISPLAY2,
      GIT_DISPLAY  TYPE GTY_T_DISPLAY,
      GIT_DISPLAY1 TYPE GTY_T_DISPLAY1,
      GIT_DISPLAY2 TYPE GTY_T_DISPLAY2,
      LV_DATE      TYPE DATS,
      LV_TIME      TYPE TIMS,
      LV_SQNO(6)   TYPE N,
      IT_FIELDCAT  TYPE SLIS_T_FIELDCAT_ALV,
      WA_LAYOUT    TYPE SLIS_LAYOUT_ALV.

DATA: IT_BDCDATA TYPE TABLE OF BDCDATA,
      WA_BDCDATA TYPE BDCDATA.
DATA: IT_MESSTAB TYPE TABLE OF BDCMSGCOLL,
      WA_MESSTAB TYPE BDCMSGCOLL,
      MESSTAB1   LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE.
DATA: CTUMODE LIKE CTU_PARAMS-DISMODE VALUE 'N',
      CUPDATE LIKE CTU_PARAMS-UPDMODE VALUE 'A'.
