*&---------------------------------------------------------------------*
*& Include          ZPP_IBOM_CREATION_C02_ROUTINE
*&---------------------------------------------------------------------*

  BREAK BREDDY .
  IF PV_FRONT = 'X'.
    IF SY-BATCH = ' '.
      PERFORM GET_DATA CHANGING GIT_FILE.
    ENDIF.
    PERFORM PROCESS_DATA USING GIT_FILE.
    PERFORM FIELD_CATLOG.
    PERFORM DISPLAY_OUTPUT.

  ELSEIF PV_BG = 'X'.
    IF SY-BATCH = ' '.
      PERFORM GET_DATA1 CHANGING GIT_FILE1.
    ENDIF.
    PERFORM PROCESS_DATA1 USING GIT_FILE1.
    PERFORM FIELD_CATLOG1.
    PERFORM DISPLAY_OUTPUT1.

  ELSEIF PV_BG1 = 'X'.
    IF SY-BATCH = ' '.
      PERFORM GET_DATA2 CHANGING GIT_FILE2.
    ENDIF.
    PERFORM PROCESS_DATA2 USING GIT_FILE2.
    PERFORM FIELD_CATLOG2.
    PERFORM DISPLAY_OUTPUT2.

*ELSEif PV_BG2 = 'X'.
*
*  IF SY-BATCH = ' '.
*    PERFORM GET_DATA3 CHANGING GIT_FILE3.
*  ENDIF.
*  PERFORM PROCESS_DATA3 USING GIT_FILE3.
*  PERFORM FIELD_CATLOG3.
*  PERFORM DISPLAY_OUTPUT3.

  ENDIF.
