*&---------------------------------------------------------------------*
*& Include          ZMM_STOCK_REPORT_SEL
*&---------------------------------------------------------------------*
TABLES : KLAH , MARA .
SELECTION-SCREEN : BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001 .

*PARAMETERS : CAT RADIOBUTTON GROUP R1 USER-COMMAND GR1 DEFAULT 'X',
*             VEN RADIOBUTTON GROUP R1.
PARAMETERS : CATEGORY TYPE KLASSE_D ."OBLIGATORY.                ""MODIF ID GR2 ."OBLIGATORY.
*SELECT-OPTIONS : CATEGORY FOR KLAH-CLASS .
*PARAMETERS : GROUP TYPE MATKL .

*SELECT-OPTIONS : CATEGORY FOR KLAH-CLASS .
SELECT-OPTIONS : GROUP FOR MARA-MATKL NO  INTERVALS .
SELECTION-SCREEN : END OF BLOCK B1 .


DATA: BEGIN OF IT_FIN1 OCCURS 0,
        CLASS TYPE KLAH-CLASS,
      END OF IT_FIN1.
DATA: IT_RETURN1 LIKE DDSHRETVAL OCCURS 0 WITH HEADER LINE.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR CATEGORY.
  SELECT CLASS FROM KLAH INTO TABLE IT_FIN1 WHERE
    WWSKZ = '0'
  AND KLART = '026'.

  CALL FUNCTION 'F4IF_INT_TABLE_VALUE_REQUEST'
    EXPORTING
      RETFIELD        = 'CLASS'
*     PVALKEY         = ' '
      DYNPPROG        = SY-CPROG
      DYNPNR          = SY-DYNNR
*     DYNPROFIELD     =
*     STEPL           = 0
*     WINDOW_TITLE    =
*     VALUE           = ' '
      VALUE_ORG       = 'S'
*     MULTIPLE_CHOICE = ' '
*     DISPLAY         = ' '
*     CALLBACK_PROGRAM       = ' '
*     CALLBACK_FORM   = ' '
*     CALLBACK_METHOD =
*     MARK_TAB        =
*     IMPORTING
*     USER_RESET      =
    TABLES
      VALUE_TAB       = IT_FIN1
*     FIELD_TAB       =
      RETURN_TAB      = IT_RETURN1
*     DYNPFLD_MAPPING =
    EXCEPTIONS
      PARAMETER_ERROR = 1
      NO_VALUES_FOUND = 2
      OTHERS          = 3.
  IF SY-SUBRC <> 0.

  ENDIF.

*  IF IT_RETURN IS NOT INITIAL .
  WRITE IT_RETURN1-FIELDVAL TO CATEGORY.
*  ELSE.
*    LEAVE TO LIST-PROCESSING .
*  ENDIF.
  REFRESH IT_FIN1 .
