*&---------------------------------------------------------------------*
*& Include          ZMM_VK12_ZKP0_CREATE_NEW_SEL
*&---------------------------------------------------------------------*



SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS : P_FILE TYPE STRING.
PARAMETERS : p1 RADIOBUTTON GROUP GRP TYPE CHAR1 DEFAULT 'X'.
PARAMETERS : p2 RADIOBUTTON GROUP GRP TYPE CHAR1.
PARAMETERS : p3 RADIOBUTTON GROUP GRP TYPE CHAR1.
PARAMETERS : p4 RADIOBUTTON GROUP GRP TYPE CHAR1.
PARAMETERS : p5 RADIOBUTTON GROUP GRP TYPE CHAR1.
PARAMETERS : p6 RADIOBUTTON GROUP GRP TYPE CHAR1.
PARAMETERS : p7 RADIOBUTTON GROUP GRP TYPE CHAR1.
PARAMETERS : p8 RADIOBUTTON GROUP GRP TYPE CHAR1.
**PARAMETERS : P8 RADIOBUTTON GROUP GRP TYPE CHAR1 DEFAULT 'X'.
**PARAMETERS : P9 RADIOBUTTON GROUP GRP TYPE CHAR1.

*Material
*Material/Batch
*Material/Serial
*Material/EAN
*Material/Vendor
*Material/Plant




SELECTION-SCREEN END OF BLOCK B1.
