*&---------------------------------------------------------------------*
*& Include          ZMM_BAPI_STOCK_UPLOAD1_TOP
*&---------------------------------------------------------------------*

TYPES : BEGIN OF GTY_FILE,
       DOC_DATE(10),
       PSTNG_DATE(10),
       MATERIAL(40),
       PLANT(04),
       STGE_LOC(04),
       MOVE_TYPE(03),
       SPEC_STOCK ,
       VENDOR(10),
       ENTRY_QNT(15),
        END OF GTY_FILE,
        GTY_T_FILE TYPE STANDARD TABLE OF GTY_FILE.

        DATA:GWA_FILE    TYPE GTY_FILE,
     GIT_FILE    TYPE  GTY_T_FILE,
     GIT_FILE_I  TYPE GTY_T_FILE,
     GIT_FILE_IT TYPE GTY_T_FILE.

DATA:FNAME TYPE LOCALFILE,
     ENAME TYPE CHAR4.

TYPES:BEGIN OF TY_FINAL,
       matnr TYPE mara-matnr,
       CHARG TYPE MSEG-CHARG,
       mblnr type mkpf-mblnr,
       mjahr type mkpf-mjahr,
       MSGTY TYPE TEXT1,
       MSG TYPE TEXT255,
      END OF TY_FINAL,
      TT_FINAL TYPE STANDARD TABLE OF TY_FINAL.

TYPES:BEGIN OF GTY_DISPLAY,
        SNO     TYPE I,
        ID      TYPE BAPIRET2-ID,
        PO_ITEM   TYPE CHAR10,
        TYPE    TYPE BAPIRET2-TYPE,
        MESSAGE TYPE BAPIRET2-MESSAGE,
      END OF GTY_DISPLAY,
      GTY_T_DISPLAY TYPE STANDARD TABLE OF GTY_DISPLAY.

DATA: GWA_DISPLAY TYPE GTY_DISPLAY,
      GIT_DISPLAY TYPE GTY_T_DISPLAY,


      IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
      WA_LAYOUT   TYPE SLIS_LAYOUT_ALV.

DATA: IT_BDCDATA TYPE TABLE OF BDCDATA,
      WA_BDCDATA TYPE BDCDATA.
DATA: IT_MESSTAB TYPE TABLE OF BDCMSGCOLL,
      WA_MESSTAB TYPE BDCMSGCOLL,
      MESSTAB1   LIKE BDCMSGCOLL OCCURS 0 WITH HEADER LINE.
DATA: CTUMODE LIKE CTU_PARAMS-DISMODE VALUE 'A',
      CUPDATE LIKE CTU_PARAMS-UPDMODE VALUE 'S'.
