*&---------------------------------------------------------------------*
*& Include          ZMM_DOCUMENT_TRACK_FORM
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Form GET_DATA
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM GET_DATA .
  BREAK BREDDY .

*  IF QR_CODE IS NOT INITIAL OR DATE IS NOT INITIAL .
*  SELECT MAX( STATUS ) FROM ZDOC_T_TRACK INTO TABLE @DATA(IT_ZDOC)
*             WHERE QR_CODE IN @QR_CODE
*             AND CREATED_DATE IN @DATE.
**  ELSE .
*    SELECT MAX( STATUS ) FROM ZDOC_T_TRACK INTO TABLE @DATA(IT_ZDOC)
*          WHERE QR_CODE IN @QR_CODE
*          AND CREATED_DATE IN @DATE.
*  ENDIF .

*  IF SAP_ROOM IS NOT INITIAL.
*    S_STATUS-SIGN = 'I' .
*    S_STATUS-OPTION = 'EQ' .
*    S_STATUS-LOW = SPACE .
*    APPEND S_STATUS .
*    CLEAR S_STATUS .
*  ENDIF.

  IF WARH IS NOT INITIAL.
    S_STATUS-SIGN = 'I' .
    S_STATUS-OPTION = 'EQ' .
    S_STATUS-LOW = '01' .
    APPEND S_STATUS .
    CLEAR S_STATUS .
  ENDIF.

  IF ACCOUNTS IS NOT INITIAL.
    S_STATUS-SIGN = 'I' .
    S_STATUS-OPTION = 'EQ' .
    S_STATUS-LOW = '02' .
    APPEND S_STATUS .
    CLEAR S_STATUS .
    S_STATUS-SIGN = 'I' .
    S_STATUS-OPTION = 'EQ' .
    S_STATUS-LOW = '04' .
    APPEND S_STATUS .
    CLEAR S_STATUS .
  ENDIF.

  IF AUDITOR IS NOT INITIAL.
    S_STATUS-SIGN = 'I' .
    S_STATUS-OPTION = 'EQ' .
    S_STATUS-LOW = '03' .
    APPEND S_STATUS .
    CLEAR S_STATUS .
  ENDIF.


  SELECT
  ZINW_T_HDR~QR_CODE,
  ZINW_T_HDR~LIFNR ,
  ZINW_T_HDR~BILL_NUM ,
  ZINW_T_HDR~NAME1 ,
  ZDOC_T_TRACK~INWD_DOC ,
  ZDOC_T_TRACK~STATUS ,
  ZDOC_T_TRACK~CREATED_DATE ,
  ZDOC_T_TRACK~SENDER ,
  ZDOC_T_TRACK~RECEIVER
*      FROM ZINW_T_HDR INTO TABLE IT_ZINW_T_HDR
    FROM ZDOC_T_TRACK  AS ZDOC_T_TRACK
*      INNER JOIN ZINW_T_HDR AS ZINW_T_HDR ON ZDOC_T_TRACK~QR_CODE = ZINW_T_HDR~QR_CODE
    LEFT OUTER JOIN ZINW_T_HDR AS ZINW_T_HDR ON ZDOC_T_TRACK~QR_CODE = ZINW_T_HDR~QR_CODE
    INTO TABLE @GT_DATA
*      FOR ALL ENTRIES IN @IT_ZDOC
*      WHERE ZDOC_T_TRACK~STATUS = @IT_ZDOC-STATUS
    WHERE ZINW_T_HDR~LIFNR IN @VENDOR
    AND ZINW_T_HDR~BILL_NUM IN @BILL_NO
    AND ZDOC_T_TRACK~CREATED_DATE IN @DATE
    AND ZINW_T_HDR~QR_CODE IN @QR_CODE
    AND ZDOC_T_TRACK~STATUS IN @S_STATUS.

  BREAK BREDDY .
  SELECT
    QR_CODE
    INWD_DOC
    LIFNR
    NAME1
    BILL_NUM
    ERDATE
    INTO TABLE IT_ZINW_T_HDR
    FROM ZINW_T_HDR AS A WHERE STATUS = '01'
    AND ERDATE IN DATE
    AND QR_CODE IN QR_CODE
    and lifnr in VENDOR
    and BILL_NUM in BILL_NO .

  IF GT_DATA IS NOT INITIAL.
    SELECT
      ZDOC_T_TRACK~QR_CODE ,
      ZDOC_T_TRACK~INWD_DOC ,
      ZDOC_T_TRACK~STATUS FROM ZDOC_T_TRACK INTO TABLE @DATA(IT_TRACK)
      FOR ALL ENTRIES IN @GT_DATA
      WHERE QR_CODE = @GT_DATA-QR_CODE
      AND INWD_DOC = @GT_DATA-INWD_DOC
      AND STATUS IN ( '02' , '03' , '04' ).


    SELECT
    ZDOC_T_TRACK~QR_CODE ,
    ZDOC_T_TRACK~INWD_DOC ,
    ZDOC_T_TRACK~STATUS FROM ZDOC_T_TRACK INTO TABLE @DATA(IT_TRACK1)
    FOR ALL ENTRIES IN @GT_DATA
    WHERE QR_CODE = @GT_DATA-QR_CODE
    AND INWD_DOC = @GT_DATA-INWD_DOC
    AND STATUS = '03' .

  ENDIF.


  BREAK BREDDY .




  IF SAP_ROOM = 'X' .
    LOOP AT IT_ZINW_T_HDR ASSIGNING FIELD-SYMBOL(<LS_SAPR>) .
      WA_FINAL-INWD_DOC = <LS_SAPR>-INWD_DOC .
      WA_FINAL-STATUS1 = ' ' .
      WA_FINAL-STATUS = 'SAP Room' .
      WA_FINAL-SENDER = ' ' .       "<LS_TRACK>-SENDER .
      WA_FINAL-RECEIVER = ' ' .             ""<LS_TRACK>-RECEIVER .
      WA_FINAL-CREATED_DATE = <LS_SAPR>-ERDATE .
      WA_FINAL-LIFNR = <LS_SAPR>-LIFNR .
      WA_FINAL-NAME1 = <LS_SAPR>-NAME1 .
      WA_FINAL-BILL_NUM = <LS_SAPR>-BILL_NUM .
      WA_FINAL-QR_CODE = <LS_SAPR>-QR_CODE .
      APPEND  WA_FINAL TO IT_FINAL .
      CLEAR : WA_FINAL .
    ENDLOOP.
  ENDIF.

  SORT GT_DATA DESCENDING BY QR_CODE STATUS   .
  DELETE ADJACENT DUPLICATES FROM GT_DATA COMPARING QR_CODE STATUS .
  BREAK BREDDY .


  LOOP AT GT_DATA ASSIGNING FIELD-SYMBOL(<LS_TRACK>).

    IF  WARH = 'X'.
      WA_FINAL-QR_CODE = <LS_TRACK>-QR_CODE .
      WA_FINAL-INWD_DOC = <LS_TRACK>-INWD_DOC .
      WA_FINAL-STATUS1 = <LS_TRACK>-STATUS .
      WA_FINAL-STATUS = 'Warehouse' .
      WA_FINAL-SENDER = <LS_TRACK>-SENDER .
      WA_FINAL-RECEIVER = <LS_TRACK>-RECEIVER .
      WA_FINAL-CREATED_DATE = <LS_TRACK>-CREATED_DATE .
      WA_FINAL-LIFNR = <LS_TRACK>-LIFNR .
      WA_FINAL-NAME1 = <LS_TRACK>-NAME1 .
      WA_FINAL-BILL_NUM = <LS_TRACK>-BILL_NUM .
      APPEND  WA_FINAL TO IT_FINAL .
      CLEAR : WA_FINAL .

      READ TABLE IT_TRACK ASSIGNING FIELD-SYMBOL(<T_TRACK1>) WITH KEY
      QR_CODE = <LS_TRACK>-QR_CODE INWD_DOC = <LS_TRACK>-INWD_DOC .
      IF SY-SUBRC = 0.
        DELETE IT_FINAL  WHERE QR_CODE = <LS_TRACK>-QR_CODE .
      ENDIF..
      ENDIF..

*    ELSEIF <LS_TRACK>-STATUS = '02' AND ACCOUNTS = 'X' .
    IF ACCOUNTS = 'X' .

      WA_FINAL-QR_CODE = <LS_TRACK>-QR_CODE .
      WA_FINAL-INWD_DOC = <LS_TRACK>-INWD_DOC .
      WA_FINAL-STATUS1 = <LS_TRACK>-STATUS .
      WA_FINAL-STATUS = 'Accounts' .
      WA_FINAL-SENDER = <LS_TRACK>-SENDER .
      WA_FINAL-RECEIVER = <LS_TRACK>-RECEIVER .
      WA_FINAL-CREATED_DATE = <LS_TRACK>-CREATED_DATE .
      WA_FINAL-LIFNR = <LS_TRACK>-LIFNR .
      WA_FINAL-NAME1 = <LS_TRACK>-NAME1 .
      WA_FINAL-BILL_NUM = <LS_TRACK>-BILL_NUM .
      APPEND  WA_FINAL TO IT_FINAL .
      CLEAR : WA_FINAL .
      SORT IT_FINAL DESCENDING BY QR_CODE STATUS .
      DELETE ADJACENT DUPLICATES FROM IT_FINAL COMPARING QR_CODE INWD_DOC .
endif .
    IF AUDITOR = 'X'.
      WA_FINAL-QR_CODE = <LS_TRACK>-QR_CODE .
      WA_FINAL-INWD_DOC = <LS_TRACK>-INWD_DOC .
      WA_FINAL-STATUS1 = <LS_TRACK>-STATUS .
      WA_FINAL-STATUS = 'Auditor' .
      WA_FINAL-SENDER = <LS_TRACK>-SENDER .
      WA_FINAL-RECEIVER = <LS_TRACK>-RECEIVER .
      WA_FINAL-CREATED_DATE = <LS_TRACK>-CREATED_DATE .
      WA_FINAL-LIFNR = <LS_TRACK>-LIFNR .
      WA_FINAL-NAME1 = <LS_TRACK>-NAME1 .
      WA_FINAL-BILL_NUM = <LS_TRACK>-BILL_NUM .
      APPEND  WA_FINAL TO IT_FINAL .
      CLEAR : WA_FINAL .

      READ TABLE IT_TRACK ASSIGNING FIELD-SYMBOL(<T_TRACK2>) WITH KEY
      QR_CODE = <LS_TRACK>-QR_CODE INWD_DOC = <LS_TRACK>-INWD_DOC .
      IF SY-SUBRC = 0.
        DELETE IT_FINAL  WHERE QR_CODE = <LS_TRACK>-QR_CODE .
      ENDIF.
    ENDIF .
  ENDLOOP .





  IF SAP_ROOM = ' ' AND WARH = ' ' AND ACCOUNTS = ' ' AND AUDITOR = ' ' .
    IF GT_DATA IS NOT INITIAL .
      LOOP AT GT_DATA ASSIGNING FIELD-SYMBOL(<WA_TRACK>) .
        WA_FINAL-QR_CODE = <WA_TRACK>-QR_CODE .
        WA_FINAL-INWD_DOC = <WA_TRACK>-INWD_DOC .
        WA_FINAL-STATUS1 = <WA_TRACK>-STATUS .

        IF WA_FINAL-STATUS1 = '01'.
          WA_FINAL-STATUS = 'Warehouse' .
        ELSEIF WA_FINAL-STATUS1 =  '02' OR WA_FINAL-STATUS1 =  '04  '.
          WA_FINAL-STATUS = 'Accounts' .
        ELSEIF WA_FINAL-STATUS1 = '03'.
          WA_FINAL-STATUS = 'Auditor' .
        ENDIF.

        WA_FINAL-SENDER = <WA_TRACK>-SENDER .
        WA_FINAL-RECEIVER = <WA_TRACK>-RECEIVER .
        WA_FINAL-CREATED_DATE = <WA_TRACK>-CREATED_DATE .
        WA_FINAL-LIFNR = <WA_TRACK>-LIFNR .
        WA_FINAL-NAME1 = <WA_TRACK>-NAME1 .
        WA_FINAL-BILL_NUM = <WA_TRACK>-BILL_NUM .
        APPEND  WA_FINAL TO IT_FINAL .
        CLEAR : WA_FINAL .
        SORT IT_FINAL ASCENDING BY QR_CODE STATUS .
        DELETE ADJACENT DUPLICATES FROM IT_FINAL COMPARING QR_CODE INWD_DOC .
      ENDLOOP .
    ELSEIF IT_ZINW_T_HDR IS NOT INITIAL.
*        READ TABLE IT_ZINW_T_HDR1 ASSIGNING FIELD-SYMBOL(<LS_SAPR1>) WITH KEY QR_CODE = <LS_TRACK>-QR_CODE .
*
*        IF SY-SUBRC = 0 .
      LOOP AT IT_ZINW_T_HDR ASSIGNING FIELD-SYMBOL(<LS_SAPR1>).
        WA_FINAL-INWD_DOC = <LS_SAPR1>-INWD_DOC .
        WA_FINAL-STATUS1 = ' ' .
        WA_FINAL-STATUS = 'SAP Room' .
        WA_FINAL-SENDER = ' ' .       "<LS_TRACK>-SENDER .
        WA_FINAL-RECEIVER = ' ' .             ""<LS_TRACK>-RECEIVER .
        WA_FINAL-CREATED_DATE = <LS_SAPR1>-ERDATE .
        WA_FINAL-LIFNR = <LS_SAPR1>-LIFNR .
        WA_FINAL-NAME1 = <LS_SAPR1>-NAME1 .
        WA_FINAL-BILL_NUM = <LS_SAPR1>-BILL_NUM .
        WA_FINAL-QR_CODE = <LS_SAPR1>-QR_CODE .
        APPEND  WA_FINAL TO IT_FINAL .
        CLEAR : WA_FINAL .
*        ENDIF.

*      ENDIF.


      ENDLOOP .
    ENDIF.
  ENDIF.

ENDFORM.
*&---------------------------------------------------------------------*
*& Form DISPLAY
*&---------------------------------------------------------------------*
*& text
*&---------------------------------------------------------------------*
*& -->  p1        text
*& <--  p2        text
*&---------------------------------------------------------------------*
FORM DISPLAY .
  DATA : IT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
         WA_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
         WVARI       TYPE DISVARIANT.
  TYPE-POOLS : SLIS.

  REFRESH : IT_FIELDCAT .
  DATA : WA_LAYOUT TYPE SLIS_LAYOUT_ALV .
  WA_LAYOUT-ZEBRA = 'X' .
  WA_LAYOUT-COLWIDTH_OPTIMIZE = 'X' .


  WA_FIELDCAT-FIELDNAME = 'INWD_DOC'.
  WA_FIELDCAT-SELTEXT_M = 'Inward Document'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR : WA_FIELDCAT .

  WA_FIELDCAT-FIELDNAME = 'STATUS'.
  WA_FIELDCAT-SELTEXT_M = 'Physical Location'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR : WA_FIELDCAT .

  WA_FIELDCAT-FIELDNAME = 'SENDER'.
  WA_FIELDCAT-SELTEXT_M = 'Sender Name'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR : WA_FIELDCAT .

  WA_FIELDCAT-FIELDNAME = 'RECEIVER'.
  WA_FIELDCAT-SELTEXT_M = 'Receiver Name'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR : WA_FIELDCAT .

  WA_FIELDCAT-FIELDNAME = 'CREATED_DATE'.
  WA_FIELDCAT-SELTEXT_M = 'Date'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR : WA_FIELDCAT .

  WA_FIELDCAT-FIELDNAME = 'LIFNR'.
  WA_FIELDCAT-SELTEXT_M = 'Vendor Code'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR : WA_FIELDCAT .

  WA_FIELDCAT-FIELDNAME = 'NAME1'.
  WA_FIELDCAT-SELTEXT_M = 'Vendor Name'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR : WA_FIELDCAT .

  WA_FIELDCAT-FIELDNAME = 'Bill_NUM'.
  WA_FIELDCAT-SELTEXT_M = 'Bill Number'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR : WA_FIELDCAT .

  WA_FIELDCAT-FIELDNAME = 'STATUS1'.
  WA_FIELDCAT-SELTEXT_M = 'Status'.
  APPEND WA_FIELDCAT TO IT_FIELDCAT.
  CLEAR : WA_FIELDCAT .

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM      = SY-REPID
*      I_CALLBACK_USER_COMMAND = 'USER_COMMAND'
      IS_LAYOUT               = WA_LAYOUT
      IT_FIELDCAT             = IT_FIELDCAT
      I_SAVE                  = 'U'
      IS_VARIANT              = WVARI
    TABLES
      T_OUTTAB                = IT_FINAL
    EXCEPTIONS
      PROGRAM_ERROR           = 1
      OTHERS                  = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.



ENDFORM.
