*&---------------------------------------------------------------------*
*& Include          ZMM_VM_DEL_UPLOAD_TOP
*&---------------------------------------------------------------------*

TYPE-POOLS:SLIS.

TYPES:BEGIN OF TA_FLATFILE,
      KSCHL(04) ,
      LIFNR(10),
      MATNR(40) ,
      END OF TA_FLATFILE ,
            TA_T_FLATFILE TYPE STANDARD TABLE OF TA_FLATFILE.

      TYPES:BEGIN OF TY_DISPLAY,
        MATNR(40),
        TYPE          TYPE BAPI_MTYPE,
        NUMBER        TYPE SYMSGNO,
        MESSAGE_V1    TYPE MARA-MATNR,
        MESSAGE	      TYPE BAPI_MSG,
        MESSAGE1      TYPE BAPI_MSG,
      END OF TY_DISPLAY,
      TY_T_DISPLAY TYPE TABLE OF TY_DISPLAY.

      DATA:FNAME TYPE LOCALFILE,
     ENAME TYPE CHAR4.


DATA:IT_DISPLAY TYPE TY_T_DISPLAY,
     WA_DISPLAY TYPE TY_DISPLAY,
     IT_T134    TYPE TABLE OF T134,
     WA_T134    TYPE T134,
     IT_NRIV    TYPE TABLE OF NRIV,
     WA_NRIV    TYPE NRIV.

DATA : LS_HEADDATA      TYPE BAPIMATHEAD,                                            ""header data
       LT_EXTENSIONIN   TYPE STANDARD TABLE OF BAPIPAREX,                            ""extension data
       LS_EXTENSIONIN   LIKE LINE OF LT_EXTENSIONIN,
       LT_EXTENSIONINX  TYPE STANDARD TABLE OF BAPIPAREXX,
       LS_EXTENSIONINX  LIKE LINE OF LT_EXTENSIONINX,
       LT_MESSAGES      TYPE TABLE OF BAPI_MATRETURN2,
       LW_MESSAGES      TYPE BAPI_MATRETURN2,
       LS_BAPI_TE_MARA  TYPE BAPI_TE_MARA,
       LS_BAPI_TE_MARAX TYPE BAPI_TE_MARAX.
DATA: WA_MESSTAB TYPE BDCMSGCOLL.


DATA:TA_FLATFILE TYPE TA_T_FLATFILE,
     WA_FLATFILE TYPE TA_FLATFILE.
