*&---------------------------------------------------------------------*
*& Include          ZN_GSTR1_HSN_SUMMARY_TOP
*&---------------------------------------------------------------------*


TABLES:BKPF,VBRK,marc,vbrp.

TYPES:BEGIN OF TY_BKPF,
      BUKRS TYPE BUKRS,
      BELNR TYPE BELNR_D,
      GJAHR TYPE GJAHR,
      BLART TYPE BLART,
      BUDAT TYPE BUDAT,
      XBLNR TYPE XBLNR1,
      XBLNR_ALT TYPE XBLNR_ALT,
      AWKEY TYPE AWKEY,
 END OF TY_BKPF.

TYPES:BEGIN OF TY_BSEG,
      BUKRS TYPE BUKRS,
      BELNR TYPE BELNR_D,
      GJAHR TYPE GJAHR,
      BUZEI TYPE BUZEI,
      BSCHL TYPE BSCHL,
      SHKZG TYPE SHKZG,
      DMBTR TYPE DMBTR,
      HWBAS TYPE HWBAS,
      TXGRP TYPE TXGRP,
      KTOSL TYPE KTOSL,
      VBELN TYPE VBELN_VF,
      HKONT TYPE HKONT,
      KUNNR TYPE KUNNR,
      BUPLA TYPE BUPLA,
      HSN_SAC TYPE J_1IG_HSN_SAC,
      REBZG  TYPE REBZG,
      WRBTR  TYPE WRBTR,
 END OF TY_BSEG.

TYPES:BEGIN OF TY_KNA1,
    KUNNR  TYPE KUNNR,
    NAME1	 TYPE NAME1_GP,
    NAME2	 TYPE NAME2_GP,
    STCD3  TYPE STCD3,
    ADRNR  TYPE ADRNR,
    REGIO  TYPE REGIO,
  END OF TY_KNA1.

TYPES:BEGIN OF TY_KONV,
    KNUMV  TYPE	KNUMV,
    KPOSN	 TYPE KPOSN,
    KSCHL	 TYPE KSCHA,
    KNUMH	 TYPE KNUMH,
    KOPOS	 TYPE KOPOS_LONG,
    KWERT	 TYPE VFPRC_ELEMENT_VALUE,
    KBETR	 TYPE VFPRC_ELEMENT_VALUE,
 END OF TY_KONV.


TYPES:BEGIN OF TY_MARC,
     MATNR TYPE MATNR,
     WERKS TYPE WERKS_D,
     STEUC TYPE  STEUC,
 END OF TY_MARC,

 BEGIN OF TY_T604N,
     SPRAS  TYPE SPRAS,
     LAND1  TYPE LAND1,
     STEUC  TYPE STEUC,
     TEXT1  TYPE BEZEI60,
 END OF TY_T604N.

TYPES:BEGIN OF TY_MAKT,
    MATNR  TYPE MATNR,
    MAKTX  TYPE MAKTX,
 END OF TY_MAKT.

TYPES:BEGIN OF TY_ADRC,
   ADDRNUMBER TYPE  AD_ADDRNUM,
   EXTENSION1 TYPE AD_EXTENS1,
   TEL_NUMBER TYPE char30,
  END OF TY_ADRC.

TYPES:BEGIN OF TY_ADR6,
  ADDRNUMBER TYPE AD_ADDRNUM,
  SMTP_ADDR  TYPE AD_SMTPADR,
  END OF TY_ADR6.

TYPES:BEGIN OF TY_VBRK,
   VBELN   TYPE VBELN_VF,    ""Billing Document
   FKART   TYPE FKART,       "Billing Type
   VKORG   TYPE VKORG,
   VTWEG   TYPE VTWEG,
   KNUMV   TYPE KNUMV,       ""dondition no
   FKDAT   TYPE FKDAT,       ""date
   LAND1   TYPE LLAND,
   REGIO   TYPE REGIO,       ""region
   KUNRG   TYPE KUNRG,       ""Payer
   KUNAG   TYPE KUNAG,       ""Sold-to party
   SPART   TYPE SPART,
   XBLNR   TYPE XBLNR_V1,
   EXNUM   TYPE EXNUM,
   GJAHR   TYPE GJAHR,
   WAERK   TYPE VBRK-WAERK,
   KURRF   TYPE VBRK-KURRF,
   BELNR   TYPE BELNR_D,
 END OF TY_VBRK.

TYPES:BEGIN OF TY_VBRP,
   VBELN   TYPE VBELN_VF,    ""Billing Document
   NETWR   TYPE NETWR_FP,
   POSNR   TYPE POSNR_VF,
   MATNR   TYPE	MATNR,
   ARKTX   TYPE ARKTX,
   WERKS   TYPE WERKS_D,
   FKIMG   TYPE FKIMG,
   VRKME   TYPE VRKME,
   SPART   TYPE SPART,
   VTWEG_AUFT TYPE VTWEG_AUFT,
   WAERK   TYPE WAERK,
   END OF TY_VBRP.

TYPES:BEGIN OF TY_EIKP,
   EXNUM  TYPE EXNUM,
   ALAND  TYPE HLAND,
   LADEL  TYPE LADEL,
  END OF  TY_EIKP.

TYPES:BEGIN OF TY_FIN,
  SLNO      TYPE CHAR5,
  BLART     TYPE FKART,
  STEUC     TYPE STEUC,
*  matnr     TYPE matnr,    "Material
*  VBELN     TYPE VBELN_VF, "Billing Document
*  POSNR     TYPE POSNR_VF, "Billing Item
*  FKDAT     TYPE FKDAT,    "Billing Date
  MAKTX     TYPE MAKTX,
  FKIMG     TYPE FKIMG,
  VRKME     TYPE VRKME,
*  TAXBLVAL  TYPE KBETR,
  netwr     type vbrp-netwr,
  IGST      TYPE KBETR,
  CGST      TYPE KBETR,
  SGST      TYPE KBETR,
*  UGST      TYPE KBETR,
  CESS      TYPE KBETR,
  OTHER     TYPE KBETR,
  TOTINV    TYPE KBETR,
*  D18       TYPE C,

  END OF TY_FIN.

TYPES: BEGIN OF TY_VBFA,
  VBELV	TYPE VBELN_VON,
  VBELN	TYPE VBELN_NACH,
END OF TY_VBFA.

TYPES:BEGIN OF TY_VBPA,
  VBELN	 TYPE VBELN_VA,
  ADRNR	 TYPE ADRNR,
  KUNNR	 TYPE KUNNR,
  PARVW  TYPE PARVW,
  END OF TY_VBPA.

TYPES:BEGIN OF TY_MSEG,
MBLNR TYPE MBLNR,
LIFNR	TYPE LIFNR,
MATNR TYPE MATNR,
END OF TY_MSEG.

TYPES:BEGIN OF TY_LFA1,
  LIFNR  TYPE LIFNR,
  LAND1	 TYPE LAND1_GP,
  NAME1	 TYPE NAME1_GP,
  NAME2	 TYPE NAME2_GP,
  STCD3  TYPE STCD3,
  REGIO  TYPE REGIO,
  TELF1  TYPE TELF1,
  END OF TY_LFA1.

DATA:WA_VBRK TYPE TY_VBRK,
     IT_VBRK TYPE TABLE OF TY_VBRK,
     WA_VBRP TYPE TY_VBRP,
     IT_VBRP TYPE TABLE OF TY_VBRP,
     WA_KNA1 TYPE TY_KNA1,
     IT_KNA1 TYPE TABLE OF TY_KNA1,
     WA_MARC TYPE TY_MARC,
     IT_MARC TYPE TABLE OF TY_MARC,
     IT_MAKT TYPE TABLE OF TY_MAKT,
     WA_MAKT TYPE TY_MAKT,
     IT_VBPA TYPE TABLE OF TY_VBPA,
     WA_VBPA TYPE TY_VBPA,
     IT_VBFA TYPE TABLE OF TY_VBFA,
     WA_VBFA TYPE TY_VBFA,
     IT_BKPF TYPE TABLE OF TY_BKPF,
     WA_BKPF TYPE TY_BKPF,
     IT_BSEG TYPE TABLE OF TY_BSEG,
     IT_BSEG1 TYPE TABLE OF TY_BSEG,
     WA_BSEG TYPE TY_BSEG,
     WA_BSEG1 TYPE TY_BSEG,
     IT_KONV TYPE TABLE OF TY_KONV,
     WA_KONV TYPE TY_KONV,
     IT_TVFKT TYPE TABLE OF TVFKT,
     WA_TVFKT TYPE TVFKT,
     IT_ADRC TYPE TABLE OF TY_ADRC,
     WA_ADRC TYPE  TY_ADRC,
     IT_ADR6 TYPE TABLE OF TY_ADR6,
     WA_ADR6 TYPE  TY_ADR6,
     IT_EIKP TYPE  TABLE OF TY_EIKP,
     WA_EIKP TYPE  TY_EIKP,
     IT_FIN  TYPE TABLE OF TY_FIN,
     IT_FIN1  TYPE TABLE OF TY_FIN,
     IT_FIN2  TYPE TABLE OF TY_FIN,
     WA_FIN  TYPE  TY_FIN,
     WA_FIN1  TYPE  TY_FIN,
     WA_FIN2  TYPE  TY_FIN,
*     WA_REGIO TYPE  ZREGION_CODES,
     IT_MSEG TYPE TABLE OF TY_MSEG,
     WA_MSEG TYPE TY_MSEG,
     WA_LFA1 TYPE TY_LFA1,
     IT_LFA1 TYPE TABLE OF TY_LFA1.



DATA:O_ALV TYPE REF TO CL_SALV_TABLE,   "Object of class cl-salv_table
     LV_MSG TYPE REF TO CX_SALV_MSG,   "#EC NEEDED "Catching exceptions
     O_FUNCTION TYPE REF TO CL_SALV_FUNCTIONS_LIST, "For setting PF-Status
     LF_EVENTS TYPE REF TO CL_SALV_EVENTS_TABLE.    "For handling double click event

DATA:C_ALV TYPE REF TO CL_GUI_ALV_GRID.

DATA:FRIGHT1    TYPE KBETR,
     FRIGHT2    TYPE KBETR,
     FRIGHT3    TYPE KBETR,
     INSURNS1   TYPE KBETR,
     INSURNS2   TYPE KBETR,
     PACKING1   TYPE KBETR,
     PACKING2   TYPE KBETR,
     OTHRS1     TYPE KBETR,
     OTHRS2     TYPE KBETR,
     OTHRS3     TYPE KBETR,
     OTHRS4     TYPE KBETR,
     OTHRS5     TYPE KBETR,
     SERVIC     TYPE KBETR,
     SUBCON     TYPE KBETR,
     TDISCNT    TYPE kbetr,
     basval     TYPE kbetr,
     ZSTO       TYPE KBETR.

DATA:INSURNS6  TYPE CHAR13,
     FRIGHT6   TYPE CHAR13,
     PACKING6  TYPE CHAR13,
     OTHRS6    TYPE CHAR13,
     TAXBLVAL2 TYPE CHAR13,
     TOTINV2   TYPE CHAR13,
     TDISCNT2  TYPE CHAR13,
     BASVAL2   TYPE CHAR13,
     SGST2     TYPE CHAR13,
     CGST2     TYPE CHAR13,
     IGST2     TYPE CHAR13,
     UGST2     TYPE CHAR13,
     CESS2     TYPE CHAR13.


TYPES:BEGIN OF T_AWKEY,
   TAWKEY TYPE AWKEY,
  END OF T_AWKEY.

DATA:W_INVAL TYPE T_AWKEY,
     T_INVAL  TYPE TABLE OF T_AWKEY.

  DATA: T_HEADER  TYPE SLIS_T_LISTHEADER,
        WA_HEADER TYPE SLIS_LISTHEADER,
        T_LINE        LIKE WA_HEADER-INFO,
        LV_NAME1      TYPE NAME1,
        LD_LINES      TYPE I,
        LD_LINESC(10) TYPE C,
        LV_TOP(255)   TYPE C.


  DATA : TDOBNAME TYPE TDOBNAME,
       IT_LINE  TYPE TABLE OF TLINE,
       WA_LINE  TYPE TLINE.
