*&---------------------------------------------------------------------*
*& Include          ZN_GSTR1_B2B_REPORT1_TOP
*&---------------------------------------------------------------------*

TABLES:VBRK,VBRP,KNA1.
TYPE-POOLS : SLIS.
DATA: IT_FCAT   TYPE SLIS_T_FIELDCAT_ALV, "WITH HEADER LINE,
      WA_FCAT   TYPE SLIS_FIELDCAT_ALV,
      WA_LAYOUT TYPE SLIS_LAYOUT_ALV.

DATA: WA_EVENTS TYPE SLIS_ALV_EVENT,
      IT_EVENTS TYPE SLIS_T_EVENT,
      IT_SORT   TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT   TYPE SLIS_SORTINFO_ALV.
DATA : I_HEADING TYPE SLIS_T_LISTHEADER .
DATA : WA_HEADING LIKE LINE OF I_HEADING.


TYPES:BEGIN OF TY_VBRK,
        VBELN TYPE VBELN_VF,
        FKART TYPE FKART,
        FKTYP TYPE FKTYP,
        FKDAT TYPE VBRK-FKDAT,
        KNUMV TYPE VBRK-KNUMV,
        FKSTO TYPE VBRK-FKSTO,
        KUNAG TYPE VBRK-KUNAG,
        XBLNR TYPE VBRK-XBLNR,
        BELNR TYPE VBRK-BELNR,
        BUKRS TYPE VBRK-BUKRS,
        STWAE TYPE VBRK-STWAE,
        WAERK TYPE VBRK-WAERK,
*        rfbsk TYPE vbrk-rfbsk,
      END OF TY_VBRK.

TYPES: BEGIN OF TY_VBRP,
         VBELN TYPE VBRP-VBELN,
         POSNR TYPE VBRP-POSNR,
         GSBER TYPE VBRP-GSBER,
         WERKS TYPE VBRP-WERKS,
         NETWR TYPE VBRP-NETWR,   "net amount
         MWSBP TYPE VBRP-MWSBP,  "tax amount
         AUBEL TYPE VBRP-AUBEL,
         matnr TYPE vbrp-MATNR,
       END OF TY_VBRP.

TYPES: BEGIN OF TY_PRCD,
         KNUMV TYPE PRCD_ELEMENTS-KNUMV,
         KPOSN TYPE PRCD_ELEMENTS-KPOSN,
         KSCHL TYPE PRCD_ELEMENTS-KSCHL,
         KAWRT TYPE PRCD_ELEMENTS-KAWRT,
         MWSK1 TYPE PRCD_ELEMENTS-MWSK1,
         KWERT TYPE PRCD_ELEMENTS-KWERT,   "  tax value
         KBETR TYPE PRCD_ELEMENTS-KBETR,   "  tax%
       END OF TY_PRCD.

TYPES:BEGIN OF TY_MARA,
        MATNR TYPE MATNR,
        MTART TYPE MTART,
      END OF TY_MARA.

TYPES:BEGIN OF TY_MARC,
        MATNR TYPE MATNR,
        STEUC TYPE  STEUC,
        WERKS TYPE WERKS_D,
      END OF TY_MARC.
TYPES:BEGIN OF TY_ZREGION,
        NEW_CODE      TYPE  REGIO,
        EXISTING_CODE TYPE  REGIO,
      END OF TY_ZREGION.
TYPES:BEGIN OF TY_MAKT,
        MATNR TYPE MATNR,
        MAKTX TYPE MAKTX,
      END OF TY_MAKT.

TYPES:BEGIN OF TY_KNA1,
        KUNNR      TYPE KUNNR,
        NAME1	     TYPE NAME1_GP,
        NAME2	     TYPE NAME2_GP,
        STCD3      TYPE STCD3,
        ADRNR      TYPE ADRNR,
        REGIO      TYPE REGIO,
        J_1IPANREF TYPE J_1IPANREF,
        LAND1      TYPE KNA1-LAND1,
      END OF TY_KNA1.


TYPES : BEGIN OF TY_T005U,
          SPRAS TYPE T005U-SPRAS,
          LAND1 TYPE T005U-LAND1,
          BLAND TYPE T005U-BLAND,
          BEZEI TYPE T005U-BEZEI,
        END OF TY_T005U.



TYPES:BEGIN OF TY_T604N,
        STEUC TYPE STEUC,
        TEXT1	TYPE BEZEI60,
      END OF TY_T604N.


TYPES:BEGIN OF TY_FIN,
        SLNO   TYPE CHAR5,
        VBELN  TYPE VBELN_VA,
        POSNR  TYPE VBRP-POSNR,
        FKDAT  TYPE VBRK-FKDAT,
        MWSK1  TYPE PRCD_ELEMENTS-MWSK1,
        NAME1  TYPE NAME1_GP,
        STCD3  TYPE STCD3,
        REGIO  TYPE REGIO,   "State Code
**        ZGSER TYPE NAME1_GP,   "Goods / Services "PENDING
        STEUC  TYPE STEUC,
        ZPOFS  TYPE NAME1_GP,   "Place of Supply
        ZSUTY  TYPE NAME1_GP,   "Supply Type
        NETWR  TYPE VBRP-NETWR,   "net amount
        SGST   TYPE KBETR,
        SGSTP  TYPE KBETR,
        CGSTP  TYPE KBETR,
        CGST   TYPE KBETR,
        IGST   TYPE KBETR,
        IGSTP  TYPE KBETR,
        UGST   TYPE KBETR,
        UGSTP  TYPE KBETR,
        CESS   TYPE KBETR,
        CESSP  TYPE KBETR,
        TCS   TYPE KBETR,
        TCSP  TYPE KBETR,
        INO   TYPE KBETR,
        INOP  TYPE KBETR,
        FRT   TYPE KBETR,
        FRTP  TYPE KBETR,
        OPS   TYPE KBETR,
        OPSP  TYPE KBETR,
        DIFF  TYPE KBETR,
        DIS   TYPE KBETR,
        TOTVAL TYPE KBETR,
        XBLNR  TYPE XBLNR_V1,
        BELNR  TYPE BELNR_D,
        STT    TYPE STRING,
        STWAE  TYPE VBRK-STWAE,
        WAERK  TYPE VBRK-WAERK,
        FKART  TYPE FKART,
        OTHERS TYPE KBETR,
**        ZOCSN TYPE NAME1_GP,  "Original Customer Name
**        ZOGST TYPE NAME1_GP,  "Original GSTIN/UIN No
**        ZODOC TYPE NAME1_GP,  "Original Document No
**        ZODDA TYPE NAME1_GP,  "Original Document Date
      END OF TY_FIN.



DATA:
  WA_KNA1    TYPE TY_KNA1,
  IT_KNA1    TYPE TABLE OF TY_KNA1,
  WA_MARA    TYPE TY_MARA,
  IT_MARA    TYPE TABLE OF TY_MARA,
  WA_MARC    TYPE TY_MARC,
  IT_MARC    TYPE TABLE OF TY_MARC,
  WA_MAKT    TYPE TY_MAKT,
  IT_VBRK    TYPE TABLE OF TY_VBRK,
  WA_VBRK    TYPE TY_VBRK,
  IT_ZREGION TYPE TABLE OF TY_ZREGION,
  WA_ZREGION TYPE TY_ZREGION,
  IT_MAKT    TYPE TABLE OF TY_MAKT,
  WA_FIN     TYPE TY_FIN,
  WA_FIN1    TYPE TY_FIN,
  WA_FIN2    TYPE TY_FIN,
  IT_FIN     TYPE TABLE OF TY_FIN,
  IT_FIN1    TYPE TABLE OF TY_FIN,
  IT_FIN2    TYPE TABLE OF TY_FIN,
  WA_T005U   TYPE TY_T005U,
  IT_T005U   TYPE TABLE OF TY_T005U,
*     WA_T005U TYPE TY_T005U,
*     IT_T005U TYPE TABLE OF TY_T005U,
  IT_T604N   TYPE TABLE OF TY_T604N,
  WA_T604N   TYPE TY_T604N,
  IT_PRCD    TYPE TABLE OF TY_PRCD,
  WA_PRCD    TYPE TY_PRCD,
  WA_VBRP    TYPE TY_VBRP,
  IT_VBRP    TYPE TABLE OF TY_VBRP.

DATA:TAXZESS  TYPE CMS_DTE_ORIGINAL_AMT,
     TAXZESS1 TYPE CMS_DTE_ORIGINAL_AMT,
     GDSVR1   TYPE CHAR50,
     ROUNDOF  TYPE PC207-BETRG,
     ROUNDOF1 TYPE PC207-BETRG,
     ROUND    TYPE PC207-BETRG,
     TAXBL2   TYPE KBETR,
     TAXBL3   TYPE KBETR,
     TAXBL4   TYPE KBETR,
     TAXBL5   TYPE KBETR,
     TOTGST1  TYPE KBETR,
     LV_NAME1 TYPE NAME1.

DATA :LV_SLN TYPE I VALUE 0.
