*&---------------------------------------------------------------------*
*& Include          ZN_GSTR1_CREDIT_SR_TOP
*&---------------------------------------------------------------------*


TABLES:VBRK,BSEG,BKPF.
TYPE-POOLS : SLIS.
DATA: IT_FCAT   TYPE SLIS_T_FIELDCAT_ALV, "WITH HEADER LINE,
      WA_FCAT   TYPE SLIS_FIELDCAT_ALV,
      WA_LAYOUT TYPE SLIS_LAYOUT_ALV.

DATA: WA_EVENTS TYPE SLIS_ALV_EVENT,
      IT_EVENTS TYPE SLIS_T_EVENT,
      IT_SORT   TYPE SLIS_T_SORTINFO_ALV,
      WA_SORT   TYPE SLIS_SORTINFO_ALV.
DATA : I_HEADING TYPE SLIS_T_LISTHEADER .
DATA : WA_HEADING LIKE LINE OF I_HEADING.


TYPES:BEGIN OF TY_BSEG,
        BUKRS	  TYPE BSEG-BUKRS,
        BELNR	  TYPE BSEG-BELNR,
        GJAHR	  TYPE BSEG-GJAHR,
*  BUDAT TYPE BUDAT,
        BSCHL	  TYPE BSEG-BSCHL,
        BUZEI   TYPE BUZEI,
        KUNNR   TYPE KUNNR,
        VBELN   TYPE VBELN_VF,
        VBEL2   TYPE VBELN_VA,
        POSN2   TYPE BSEG-POSN2,
        LIFNR	  TYPE LIFNR,
        MATNR   TYPE MATNR,
        HSN_SAC TYPE J_1IG_HSN_SAC,
        KTOSL   TYPE KTOSL,
        TXGRP	  TYPE TXGRP,
*  H_BLART TYPE BLART,
        KOART   TYPE BSEG-KOART,
        UMSKZ   TYPE BSEG-UMSKZ,
        DMBTR   TYPE BSEG-DMBTR,
        GSBER   TYPE BSEG-GSBER,
        PSWSL   TYPE BSEG-PSWSL,
      END OF TY_BSEG.

TYPES:BEGIN OF TY_BKPF,
        BUKRS	     TYPE BKPF-BUKRS,
        BELNR	     TYPE BKPF-BELNR,
        GJAHR	     TYPE BKPF-GJAHR,
        BLART	     TYPE BKPF-BLART,
        BUDAT      TYPE BKPF-BUDAT,
        TCODE      TYPE BKPF-TCODE,
        AWKEY      TYPE BKPF-AWKEY,
        XREVERSED  TYPE BKPF-XREVERSED,
        XREVERSING TYPE BKPF-XREVERSING,
        XBLNR      TYPE BKPF-XBLNR,
      END OF TY_BKPF.

TYPES:BEGIN OF TY_BSET,
        BUKRS	TYPE BUKRS,
        BELNR	TYPE BELNR_D,
        GJAHR	TYPE GJAHR,
        BUZEI TYPE BUZEI,
        TXGRP	TYPE TXGRP,
        SHKZG TYPE SHKZG,
        HWBAS	TYPE HWBAS_BSES,
        HWSTE	TYPE HWSTE,
        KTOSL TYPE KTOSL,
        KSCHL TYPE KSCHL,
        KBETR TYPE KBETR_TAX,
      END OF TY_BSET.

TYPES:BEGIN OF TY_VBAP,
        VBELN	TYPE VBELN_VA,
        POSNR TYPE VBAP-POSNR,
        MATNR	TYPE MATNR,
        WERKS TYPE VBAP-WERKS,
      END OF TY_VBAP.

TYPES:BEGIN OF TY_VBRK,
        VBELN TYPE VBELN_VF,
        FKART TYPE FKART,
        FKTYP TYPE FKTYP,
        XBLNR TYPE VBRK-XBLNR,
        FKDAT TYPE VBRK-FKDAT,
        KUNNR TYPE VBRK-KUNAG,
        WAERK TYPE VBRK-WAERK,
        ZUONR TYPE VBRK-VBELN,
      END OF TY_VBRK.

TYPES:BEGIN OF TY_MARA,
        MATNR TYPE MATNR,
        MTART TYPE MTART,
      END OF TY_MARA.

TYPES:BEGIN OF TY_MARC,
        MATNR TYPE MATNR,
        STEUC TYPE  STEUC,
        WERKS TYPE WERKS_D,
      END OF TY_MARC.

TYPES:BEGIN OF TY_ZREGION,
        NEW_CODE      TYPE  REGIO,
        EXISTING_CODE TYPE  REGIO,
      END OF TY_ZREGION.

TYPES:BEGIN OF TY_MAKT,
        MATNR TYPE MATNR,
        MAKTX TYPE MAKTX,
      END OF TY_MAKT.

TYPES:BEGIN OF TY_KNA1,
        KUNNR      TYPE KUNNR,
        NAME1	     TYPE NAME1_GP,
        NAME2	     TYPE NAME2_GP,
        STCD3      TYPE STCD3,
        ADRNR      TYPE ADRNR,
        REGIO      TYPE REGIO,
        J_1IPANREF TYPE J_1IPANREF,
        LAND1      TYPE KNA1-LAND1,
      END OF TY_KNA1.

TYPES:BEGIN OF TY_T604N,
        STEUC TYPE STEUC,
        TEXT1	TYPE BEZEI60,
      END OF TY_T604N.

TYPES : BEGIN OF TY_T005U,
          SPRAS TYPE T005U-SPRAS,
          LAND1 TYPE T005U-LAND1,
          BLAND TYPE T005U-BLAND,
          BEZEI TYPE T005U-BEZEI,
        END OF TY_T005U.

TYPES : BEGIN OF TS_VBRP,
          VBELN TYPE VBRP-VBELN,
          POSNR TYPE VBRP-POSNR,
          WERKS TYPE VBRP-WERKS,
          MATNR TYPE VBRP-MATNR,
        END OF TS_VBRP .


TYPES:BEGIN OF TY_FIN,
        SLNO   TYPE CHAR5,
        VBELN  TYPE VBELN_VA,
        LTEXT  TYPE T003T-LTEXT,
        AWKEY  TYPE BKPF-AWKEY,
        XBLNR  TYPE VBRK-XBLNR,
        ZOOR   TYPE STCD3,      "Original or Revised "pending
        NAME1  TYPE NAME1_GP,
        STCD3  TYPE STCD3,
        REGIO  TYPE REGIO,   "State Code
        BELNR  TYPE BELNR,
        BUDAT  TYPE BUDAT,
        ZGSER  TYPE NAME1_GP,   "Goods / Services "PENDING
        STEUC  TYPE STEUC,
        ZPOFS  TYPE NAME1_GP,   "Place of Supply
        ZSUTY  TYPE NAME1_GP,   "Supply Type
        DMBTR  TYPE DMBTR,
        SGST   TYPE KBETR,
        SGSTP  TYPE KBETR,
        CGSTP  TYPE KBETR,
        CGST   TYPE KBETR,
        IGST   TYPE KBETR,
        IGSTP  TYPE KBETR,
        UGST   TYPE KBETR,
        UGSTP  TYPE KBETR,
        CESS   TYPE KBETR,
        CESSP  TYPE KBETR,
        TOTVAL TYPE KBETR,
        XBLNRC TYPE BKPF-XBLNR,
        BUDATD TYPE BKPF-BUDAT,
        BELNR1 TYPE BSEG-BELNR,
        FKDAT  TYPE VBRK-FKDAT,
        STT    TYPE STRING,
        FKART  TYPE VBRK-FKART,
        WAERK  TYPE VBRK-WAERK,
        ZUONR TYPE VBRK-ZUONR,
        oinv TYPE vbrk-XBLNR,

      END OF TY_FIN.



DATA:
  WA_KNA1    TYPE TY_KNA1,
  IT_KNA1    TYPE TABLE OF TY_KNA1,
  WA_MARA    TYPE TY_MARA,
  IT_MARA    TYPE TABLE OF TY_MARA,
  WA_MARC    TYPE TY_MARC,
  IT_MARC    TYPE TABLE OF TY_MARC,
  WA_MAKT    TYPE TY_MAKT,
  IT_VBRK    TYPE TABLE OF TY_VBRK,
  IT_VBRK1    TYPE TABLE OF TY_VBRK,
  WA_VBRK    TYPE TY_VBRK,
  WA_VBRK1    TYPE TY_VBRK,
  IT_ZREGION TYPE TABLE OF TY_ZREGION,
  WA_ZREGION TYPE TY_ZREGION,
  IT_MAKT    TYPE TABLE OF TY_MAKT,
  IT_VBRP    TYPE TABLE OF TS_VBRP,
  WA_VBRP    TYPE TS_VBRP,
  WA_FIN     TYPE TY_FIN,
  WA_FIN1    TYPE TY_FIN,
  WA_FIN2    TYPE TY_FIN,
  WA_FIN3    TYPE TY_FIN,
  IT_FIN     TYPE TABLE OF TY_FIN,
  IT_FIN1    TYPE TABLE OF TY_FIN,
  IT_FIN2    TYPE TABLE OF TY_FIN,
  IT_FIN3    TYPE TABLE OF TY_FIN,
  WA_T005U   TYPE TY_T005U,
  IT_T005U   TYPE TABLE OF TY_T005U,
  IT_T604N   TYPE TABLE OF TY_T604N,
  WA_T604N   TYPE TY_T604N,
  IT_BSEG1   TYPE TABLE OF TY_BSEG,
  IT_BSEG    TYPE TABLE OF TY_BSEG,
  WA_BSEG    TYPE TY_BSEG,
  WA_BSEG1   TYPE TY_BSEG,
  IT_BSET    TYPE TABLE OF TY_BSET,
  WA_BSET    TYPE TY_BSET,
  IT_BKPF    TYPE TABLE OF TY_BKPF,
  WA_BKPF    TYPE TY_BKPF,
  WA_VBAP    TYPE TY_VBAP,
  IT_VBAP    TYPE TABLE OF TY_VBAP.

DATA:TAXZESS  TYPE CMS_DTE_ORIGINAL_AMT,
     TAXZESS1 TYPE CMS_DTE_ORIGINAL_AMT,
     GDSVR1   TYPE CHAR50,
     ROUNDOF  TYPE PC207-BETRG,
     ROUNDOF1 TYPE PC207-BETRG,
     ROUND    TYPE PC207-BETRG,
     TAXBL2   TYPE KBETR,
     TAXBL3   TYPE KBETR,
     TAXBL4   TYPE KBETR,
     TAXBL5   TYPE KBETR,
     TAXB16   TYPE KBETR,
     TOTGST1  TYPE KBETR,
     LV_NAME1 TYPE BUTXT.
