FUNCTION ZPARENT_DETAILS.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  EXPORTING
*"     VALUE(ET_DISPLAY) TYPE  ZPAR_DET_TT
*"----------------------------------------------------------------------
  DATA :WA_PARENT  TYPE ZPAR_DET,
        IT_O_WGH01 TYPE TABLE OF WGH01,
        WA_O_WGH01 TYPE WGH01.

*  TYPES : BEGIN OF TY_TEST,
*            ZZARTICLE TYPE MARA-ZZARTICLE,
*            MATKL     TYPE MARA-MATKL,
*            HYR       TYPE WWGHA,
*          END OF TY_TEST.

*  DATA: LT_TEST TYPE TABLE OF TY_TEST.
*  BREAK BREDDY.
  SELECT MARA~MATNR , MARA~MATKL , MARA~ZZARTICLE , MARA~ATTYP  FROM MARA INTO TABLE @DATA(IT_MARA) where attyp ne '01'.
  DATA(IT_MARA_MG) = IT_MARA.
  SORT IT_MARA_MG BY MATKL.
  DELETE ADJACENT DUPLICATES FROM IT_MARA_MG COMPARING MATKL .
*  DELETE IT_MARA_MG WHERE ATTYP = '01'.
  DELETE IT_MARA_MG WHERE ZZARTICLE EQ SPACE .

  LOOP AT IT_MARA_MG ASSIGNING FIELD-SYMBOL(<WA_MARA>).

    WA_PARENT-PARENT_TEXT = <WA_MARA>-ZZARTICLE.


    CALL FUNCTION 'MERCHANDISE_GROUP_HIER_ART_SEL'
      EXPORTING
        MATKL       = <WA_MARA>-MATKL
        SPRAS       = SY-LANGU
      TABLES
        O_WGH01     = IT_O_WGH01
      EXCEPTIONS
        NO_BASIS_MG = 1
        NO_MG_HIER  = 2
        OTHERS      = 3.
    IF SY-SUBRC <> 0.
* Implement suitable error handling here
    ENDIF.

    READ TABLE IT_O_WGH01 INTO WA_O_WGH01 INDEX 1 .

    IF WA_O_WGH01-WWGHB CA '*' .
    ELSE .
      WA_PARENT-GROUP_ID = WA_O_WGH01-WWGHA.
      CLEAR :  WA_O_WGH01.
    ENDIF.

*    APPEND VALUE #( ZZARTICLE = <WA_MARA>-ZZARTICLE MATKL = <WA_MARA>-MATKL HYR = WA_O_WGH01-WWGHA ) TO LT_TEST.
*    WA_PARENT-MATKL = <WA_MARA>-MATKL.
    APPEND WA_PARENT TO ET_DISPLAY.
    CLEAR : WA_PARENT.
  ENDLOOP.
  BREAK BREDDY.
  SORT ET_DISPLAY BY PARENT_TEXT GROUP_ID .
*  BREAK BREDDY.
  DELETE ADJACENT DUPLICATES FROM ET_DISPLAY COMPARING PARENT_TEXT GROUP_ID.
  DELETE ET_DISPLAY WHERE GROUP_ID eq ' '.
*  DELETE ET_DISPLAY WHERE PARENT_TEXT EQ SPACE.
*  DELETE ET_DISPLAY WHERE PARENT_TEXT IS INITIAL.
BREAK breddy.
ENDFUNCTION.
