FUNCTION ZMATERIAL_GROUP_DET.
*"----------------------------------------------------------------------
*"*"Local Interface:
*"  IMPORTING
*"     VALUE(IM_INPUT) TYPE  INPUT OPTIONAL
*"  EXPORTING
*"     VALUE(ET_DISPLAY) TYPE  ZMAT_GR_TT
*"----------------------------------------------------------------------
*  DATA : WA_MAT_DESC TYPE ZMAT_DESC.
**  BREAK BREDDY.
*  SELECT  T023~MATKL ,T023T~WGBEZ ,  T023T~WGBEZ60 FROM T023 AS T023
**    LEFT OUTER JOIN T023 AS T023 ON T023~MATKL = MARA~MATKL
*    LEFT OUTER JOIN T023T AS T023T ON T023T~MATKL = T023~MATKL
*    INTO TABLE @DATA(IT_T023)
*    WHERE T023T~SPRAS = @SY-LANGU.
*  ""ERSDA BETWEEN @IM_DATE_FROM AND @IM_DATE_TO OR LAEDA BETWEEN @IM_DATE_FROM AND @IM_DATE_TO AND T023T~SPRAS = @SY-LANGU.
*
*  LOOP AT IT_T023 ASSIGNING FIELD-SYMBOL(<WA_T023>).
*
*    WA_MAT_DESC-MAT_GROUP = <WA_T023>-MATKL.
*    WA_MAT_DESC-MAT_DESC  = <WA_T023>-WGBEZ60.
**    WA_MAT_DESC-MAT_DESC  = <WA_T023>-WGBEZ.
*
*    APPEND WA_MAT_DESC TO ET_DISPLAY.
*    CLEAR : WA_MAT_DESC.
*  ENDLOOP.

*** Start of Chnages By Suri 01.07.2019
*** For sending Material Group - Vendor Link

*  SELECT DISTINCT T023T~MATKL, T023T~WGBEZ60, A502~LIFNR
*         INTO TABLE @ET_DISPLAY
*         FROM T023T AS T023T
*         INNER JOIN MARA AS MARA ON MARA~MATKL = T023T~MATKL
*         left JOIN A502 AS A502 ON MARA~MATNR = A502~MATNR
*         left JOIN KONP AS KONP ON KONP~KNUMH = A502~KNUMH
*         WHERE A502~KSCHL = 'PB00' AND MARA~ATTYP <> '01' AND T023T~SPRAS = @SY-LANGU
*         AND A502~DATBI GE @SY-DATUM AND A502~DATAB LE @SY-DATUM AND KONP~LOEVM_KO = @SPACE
*         GROUP BY T023T~MATKL , T023T~WGBEZ60, A502~LIFNR.


  SELECT DISTINCT T023T~MATKL, T023T~WGBEZ60, A502~LIFNR
         INTO TABLE @ET_DISPLAY
         FROM T023T AS T023T
         INNER JOIN MARA AS MARA ON MARA~MATKL = T023T~MATKL
         LEFT JOIN A502 AS A502 ON MARA~MATNR = A502~MATNR AND A502~KSCHL = 'PB00' AND A502~DATBI GE @SY-DATUM AND A502~DATAB LE @SY-DATUM
         LEFT JOIN KONP AS KONP ON KONP~KNUMH = A502~KNUMH AND KONP~LOEVM_KO = @SPACE
         WHERE MARA~ATTYP <> '01' AND T023T~SPRAS = @SY-LANGU
         GROUP BY T023T~MATKL , T023T~WGBEZ60, A502~LIFNR.

*** Start of Chnages By Suri 01.07.2019
ENDFUNCTION.
