*&---------------------------------------------------------------------*
*& Report ZPRINT_LABLES
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZPRINT_LABLES.
CONSTANTS : C_X(1)  VALUE 'X',
            C_03(1) VALUE '03'.
PARAMETERS : P_QR TYPE ZQR_CODE.

SELECT SINGLE * FROM ZINW_T_HDR INTO @DATA(LS_HDR) WHERE QR_CODE = @P_QR AND STATUS GE @C_03.
IF LS_HDR-LABLE_PRINT IS INITIAL.
  IF  LS_HDR-MBLNR IS NOT INITIAL .
    SELECT SINGLE MJAHR FROM MSEG INTO @DATA(LV_MJAHR) WHERE MBLNR = @LS_HDR-MBLNR.
    DATA(LV_MBLNR) = LS_HDR-MBLNR.
  ELSE.
    SELECT SINGLE MJAHR FROM MSEG INTO LV_MJAHR WHERE MBLNR = LS_HDR-MBLNR_103.
    LV_MBLNR = LS_HDR-MBLNR_103.
  ENDIF.
*** Printing Lables
  IF LV_MBLNR IS NOT INITIAL AND LV_MJAHR IS NOT INITIAL.
    SUBMIT ZTP3_LABLE AND RETURN WITH P_MBLNR = LV_MBLNR WITH P_TP3 = C_X WITH P_MJAHR = LV_MJAHR.
    IF SY-SUBRC = 0 AND SY-UCOMM = 'PRNT'.
***   Updating Printing status
      LS_HDR-LABLE_PRINT = C_X.
      LS_HDR-L_PRINTED_BY = SY-UNAME.
      MODIFY ZINW_T_HDR FROM LS_HDR.
    ENDIF.
  ENDIF.
ELSE.
  MESSAGE S026(ZMSG_CLS) WITH LS_HDR-L_PRINTED_BY DISPLAY LIKE 'E'.
  LEAVE LIST-PROCESSING.
ENDIF.
