*&---------------------------------------------------------------------*
*& Include          ZSALFORMP_TOP
*&---------------------------------------------------------------------*

*REPORT ZSALFORMP.
TABLES: PA0001,PA0021,PERNR.
TYPE-POOLS: SLIS.

TYPES: BEGIN OF TY_PA0001,
         PERNR TYPE PA0001-PERNR,
         ENAME TYPE PA0001-ENAME,
       END OF TY_PA0001,

       BEGIN OF TY_PA0021,
         PERNR TYPE PA0021-PERNR,
         FAMSA TYPE PA0021-FAMSA,
         FAVOR TYPE PA0021-FAVOR,
         FANAM TYPE PA0021-FANAM,
       END OF TY_PA0021,

       BEGIN OF TY_FINAL,
         SL           TYPE I,
         PERNR        TYPE PA0001-PERNR,
         ENAME        TYPE PA0001-ENAME,
         FAMSA        TYPE PA0021-FAMSA,
         NAME         TYPE T591S-STEXT,
         NOMINEE(30)  TYPE C,
*         RELATION(40) TYPE C,
       END OF TY_FINAL,

       BEGIN OF TY_T591S,
         SPRSL TYPE T591S-SPRSL,
         INFTY TYPE T591S-INFTY,
         SUBTY TYPE T591S-SUBTY,
         STEXT TYPE T591S-STEXT,
       END OF TY_T591S.


DATA: IT_PA0001 TYPE TABLE OF TY_PA0001,
      WA_PA0001 TYPE  TY_PA0001,
      IT_PA0021 TYPE TABLE OF TY_PA0021,
      WA_PA0021 TYPE  TY_PA0021,
      IT_T591S  TYPE TABLE OF TY_T591S,
      WA_T591S  TYPE TY_T591S,
      WA_FINAL  TYPE TY_FINAL,
      IT_FINAL  TYPE TABLE OF TY_FINAL,
      WA_FCAT   TYPE SLIS_FIELDCAT_ALV,
      IT_FCAT   TYPE SLIS_T_FIELDCAT_ALV,
      WA_LAYOUT TYPE SLIS_LAYOUT_ALV,
      T_HEADER  TYPE SLIS_T_LISTHEADER,
      WA_HEADER TYPE SLIS_LISTHEADER,
      SL        TYPE I,
      WA_ITEM   TYPE ZSAL_FORMP_STR,
      IT_ITEM   TYPE ZSAL_FORMP_STR_TT.
