*&---------------------------------------------------------------------*
*& Include ZSAP_DEBITNOTETOP                        - Module Pool      ZSAP_DEBITNOTE
*&---------------------------------------------------------------------*
PROGRAM ZSAP_DEBITNOTE.

TYPES: BEGIN OF TY_MSEG,
         MBLNR TYPE MSEG-MBLNR,     "MATERIAl DOCUMENT
         MJAHR TYPE MSEG-MJAHR,
         ZEILE TYPE MSEG-ZEILE,
         CHARG TYPE MSEG-CHARG,     "BATCH
         MATNR TYPE MSEG-MATNR,
         BWART TYPE MSEG-BWART,
         EBELN TYPE MSEG-EBELN,
       END OF TY_MSEG,

       BEGIN OF TY_EKKO,
*         MANDT TYPE EKKO-MANDT,
         EBELN TYPE EKKO-EBELN,     "PO#
         KNUMV TYPE EKKO-KNUMV,
         LIFNR TYPE EKKO-LIFNR,
         AEDAT TYPE EKKO-AEDAT,
       END OF TY_EKKO,

       BEGIN OF TY_EKPO,
         EBELN TYPE EKPO-EBELN,
         EBELP TYPE EKPO-EBELP,
         MATNR TYPE EKPO-MATNR,     "SST CODE
         MEINS TYPE EKPO-MEINS,     "unit
         MENGE TYPE EKPO-MENGE,     "qty
         NETPR TYPE EKPO-NETPR,     "AMOUNT
         BUKRS TYPE EKPO-BUKRS,     "COMP CODE
         WERKS TYPE EKPO-WERKS,     "PLANT
       END OF TY_EKPO,

       BEGIN OF TY_PRCD_ELEMENTS,
         KNUMV TYPE PRCD_ELEMENTS-KNUMV,
         KPOSN TYPE PRCD_ELEMENTS-KPOSN,
         STUNR TYPE PRCD_ELEMENTS-STUNR,
         ZAEHK TYPE PRCD_ELEMENTS-ZAEHK,
         KBETR TYPE PRCD_ELEMENTS-KBETR,    "gst%
         KWERT TYPE PRCD_ELEMENTS-KWERT,    "GST
       END OF TY_PRCD_ELEMENTS,

       BEGIN OF TY_ZINW_T_ITEM,
         QR_CODE TYPE ZINW_T_ITEM-QR_CODE,
         EBELN   TYPE ZINW_T_ITEM-EBELN,
         EBELP   TYPE ZINW_T_ITEM-EBELP,
*         SNO     TYPE ZINW_T_ITEM-SNO,
         MATNR   TYPE ZINW_T_ITEM-MATNR,
       END OF TY_ZINW_T_ITEM.

TYPES: BEGIN OF TY_HDR,
         EBELN   TYPE EBELN,
         QR_CODE TYPE ZQR_CODE,
       END OF TY_HDR.

TYPES: BEGIN OF TY_DET,
         EBELN       TYPE EBELN,
         MBLNR       TYPE MBLNR,
         MJAHR       TYPE MJAHR,
         MSG_TYPE(1),
         MESSAGE     TYPE BAPIRET2-MESSAGE,
       END OF TY_DET.

*TYPES: BEGIN OF TY_ITEM,
*         QR_CODE TYPE    ZQR_CODE,
*         EBELN   TYPE    EBELN,
*         EBELP   TYPE    EBELP,
*         MATNR   TYPE    MATNR,
*         LGORT   TYPE    LGORT_D,
*         WERKS   TYPE    EWERK,
*         MAKTX   TYPE    MAKTX,
*         MATKL   TYPE    MATKL,
*         MENGE_P TYPE    ZMENGE_P,
*         MEINS   TYPE    BSTME,
*       END OF TY_ITEM.

TYPES: BEGIN OF TY_T001W,
         WERKS TYPE WERKS_D,
         EKORG TYPE EKORG,
       END OF TY_T001W.

TYPES: BEGIN OF TY_MARC,
         MATNR TYPE MARC-MATNR,
         WERKS TYPE MARC-WERKS,
         EKGRP TYPE MARC-EKGRP,
       END OF TY_MARC,

       BEGIN OF TY_MARA,
         MATNR TYPE MATNR,
         MATKL TYPE MATKL,
       END OF TY_MARA,

       BEGIN OF TY_MARD,
         MATNR TYPE MATNR,
         WERKS TYPE WERKS_D,
         LGORT TYPE LGORT_D,
       END OF TY_MARD.


DATA: IT_MSEG          TYPE TABLE OF TY_MSEG,
      WA_MSEG          TYPE  TY_MSEG,
      IT_EKKO          TYPE TABLE OF TY_EKKO,
      WA_EKKO          TYPE  TY_EKKO,
      IT_EKPO          TYPE TABLE OF TY_EKPO,
      WA_EKPO          TYPE  TY_EKPO,
      IT_ITEM          TYPE TABLE OF ZDEBIT_NOTE,
      WA_ITEM          TYPE ZDEBIT_NOTE,
      IT_ITEM1         TYPE TABLE OF ZDEBIT_NOTE,
      WA_ITEM1         TYPE ZDEBIT_NOTE,
      IT_ITEM2         TYPE TABLE OF ZDEBIT_NOTE,
      WA_ITEM2         TYPE ZDEBIT_NOTE,
      IT_PRCD_ELEMENTS TYPE TABLE OF TY_PRCD_ELEMENTS,
      WA_PRCD_ELEMENTS TYPE TY_PRCD_ELEMENTS,
      IT_ZINW_T_ITEM   TYPE TABLE OF TY_ZINW_T_ITEM,
      WA_ZINW_T_ITEM   TYPE TY_ZINW_T_ITEM,
      WA_HEADER        TYPE ZSST_HEADER,
      IT_T001W         TYPE TABLE OF TY_T001W,
      WA_T001W         TYPE TY_T001W,
      IT_MARC          TYPE TABLE OF TY_MARC,
      WA_MARC          TYPE TY_MARC,
      IT_MARA          TYPE TABLE OF TY_MARA,
      WA_MARA          TYPE TY_MARA,
      IT_MARD          TYPE TABLE OF TY_MARD,
      WA_MARD          TYPE TY_MARD,
      LV_LIFNR         TYPE LFA1-LIFNR,
      LV_BATCH         TYPE MSEG-CHARG,
      LV_QR_CODE       TYPE ZQR_CODE,
      LV_MBLNR         TYPE MSEG-MBLNR,
      LV_MATNR         TYPE MSEG-MATNR,
      LV_MENGE         TYPE BSTMG,
*      LV_GST           TYPE VFPRC_ELEMENT_AMOUNT,
*      LV_AMOUNT        TYPE BPREI,
      SLNO             TYPE I,
      LV_GST%          TYPE KBETR_KOND,
      LT_HDR           TYPE STANDARD TABLE OF TY_HDR,
*       LT_ITEM TYPE STANDARD TABLE OF TY_ITEM,
      LT_DET           TYPE STANDARD TABLE OF TY_DET.


*** Work area Declarations
DATA: "WA_ITEM TYPE TY_ITEM,
      WA_DET  TYPE TY_DET.

FIELD-SYMBOLS : <LS_BAPIRET> TYPE BAPIRET2.

DATA: TY_TOOLBAR       TYPE STB_BUTTON,
      CUSTOM_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GRID             TYPE REF TO CL_GUI_ALV_GRID,
      GS_LAYOUT        TYPE LVC_S_LAYO,
      GS_FIELDCAT      TYPE LVC_S_FCAT,
      GI_FIELDCAT      TYPE LVC_T_FCAT,
      MYCONTAINER      TYPE SCRFNAME VALUE 'MYCONTAINER',
      GS_EXCLUDE       TYPE UI_FUNC,
      GT_TLBR_EXCL     TYPE UI_FUNCTIONS.

CLASS EVENT_CLASS DEFINITION DEFERRED.
DATA: LR_EVENT    TYPE REF TO EVENT_CLASS,
      LV_EBELN    TYPE EBELN,
      LV_MSG(100) TYPE C.

DATA: HEADER      LIKE BAPIMEPOHEADER,
      HEADERX     LIKE BAPIMEPOHEADERX,
      ITEM        TYPE TABLE OF BAPIMEPOITEM  WITH HEADER LINE,
      POSCHEDULE  TYPE TABLE OF BAPIMEPOSCHEDULE WITH HEADER LINE,
      POSCHEDULEX TYPE TABLE OF BAPIMEPOSCHEDULX WITH HEADER LINE,
      ITEMX       TYPE TABLE OF BAPIMEPOITEMX  WITH HEADER LINE,
      RETURN      TYPE TABLE OF BAPIRET2,
      WA_RETURN   TYPE  BAPIRET2,
      LV_SUC(100) TYPE C.

CLASS EVENT_CLASS DEFINITION.

  PUBLIC SECTION.

    CLASS-METHODS:
      HANDLE_TOOLBAR_SET
            FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
        IMPORTING
            E_OBJECT
            E_INTERACTIVE,
      HANDLE_USER_COMMAND FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
        IMPORTING
            E_UCOMM
            SENDER.
ENDCLASS.

CLASS EVENT_CLASS IMPLEMENTATION.

  METHOD HANDLE_TOOLBAR_SET.
    READ TABLE E_OBJECT->MT_TOOLBAR TRANSPORTING NO FIELDS WITH KEY FUNCTION = 'ADD'.
    IF SY-SUBRC = 0.
      RETURN.
    ENDIF.
    CLEAR TY_TOOLBAR.
    TY_TOOLBAR-FUNCTION = 'ADD'. "name of btn to  catch click
    TY_TOOLBAR-BUTN_TYPE = 0.
*    ty_toolbar-ICON =
    TY_TOOLBAR-TEXT = 'Add Record'.
    APPEND TY_TOOLBAR TO E_OBJECT->MT_TOOLBAR.
  ENDMETHOD.

  METHOD HANDLE_USER_COMMAND.

    CASE E_UCOMM.
      WHEN CL_GUI_ALV_GRID=>MC_FC_LOC_APPEND_ROW.
        APPEND INITIAL LINE TO IT_ITEM1.

      WHEN OTHERS.
    ENDCASE.

  ENDMETHOD.                    "handle_user_command

ENDCLASS.
