*&---------------------------------------------------------------------*
*& Include ZSAPMP_MM_GOODS_RETURN_PO_TOP            - Module Pool      ZSAPMP_MM_GOODS_RETURN_PO
*&---------------------------------------------------------------------*
PROGRAM ZSAPMP_MM_GOODS_RETURN_PO.
DATA: OK_CODE LIKE SY-UCOMM.
DATA : LV_EBELN      TYPE EBELN,
       GV_MBLNR_N    TYPE MBLNR,
       LV_DEBIT_NOTE TYPE RE_BELNR.
DATA: IT_O_WGH01   TYPE TABLE OF WGH01,
      IT_O_WGH01_B TYPE TABLE OF WGH01,
      WA_O_WGH01_B TYPE WGH01,
      WA_O_WGH01   TYPE WGH01.
TYPES : BEGIN OF TY_MSEG,
          BWART TYPE BWART,
          MATNR TYPE MATNR,
          WERKS TYPE WERKS_D,
          CHARG TYPE CHARG_D,
          LIFNR TYPE ELIFN,
          EBELN TYPE EBELN,
        END OF TY_MSEG .

TYPES : BEGIN OF TY_MBEW ,
          MATNR TYPE MATNR,
          BWKEY TYPE BWKEY,
          BWTAR TYPE BWTAR_D,
          LBKUM TYPE LBKUM,

          VERPR TYPE VERPR,
        END OF TY_MBEW .

TYPES : BEGIN OF TY_FINAL ,
          MATNR    TYPE MATNR,
          WERKS    TYPE WERKS_D,
          LIFNR    TYPE ELIFN,
          VERPR    TYPE VERPR,
          CHARG    TYPE CHARG_D,
          QUANTITY TYPE LBKUM,
          EKGRP    TYPE EKGRP,
          VALUE    TYPE VERPR,
          NAME1    TYPE NAME1_GP,
          TAX_PER  TYPE NETPR,
          TAX_VAL  TYPE NETPR,
        END OF TY_FINAL.

DATA : IT_MSEG  TYPE TABLE OF TY_MSEG,
       IT_LIF   TYPE TABLE OF TY_MSEG,
       WA_MSEG  TYPE TY_MSEG,
       IT_MBEW  TYPE TABLE OF TY_MBEW,
       WA_MBEW  TYPE  TY_MBEW,
       IT_FINAL TYPE TABLE OF TY_FINAL,
       WA_FINAL TYPE  TY_FINAL.

DATA : LV_BATCH TYPE CHARG_D .

DATA:CONTAINER   TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
     GRID        TYPE REF TO CL_GUI_ALV_GRID,
     IT_EXCLUDE  TYPE UI_FUNCTIONS,
     LW_LAYO     TYPE LVC_S_LAYO,
     LT_FIELDCAT TYPE  LVC_T_FCAT.
DATA: LT_EXCLUDE TYPE UI_FUNCTIONS.
DATA : LS_STABLE TYPE LVC_S_STBL.
DATA : REF_GRID TYPE REF TO CL_GUI_ALV_GRID.
DATA : LV_PLANT TYPE BWKEY .
