*&---------------------------------------------------------------------*
*& Include          ZSAPMP_MM_PO_CREATE_I01
*&---------------------------------------------------------------------*

*&SPWIZARD: INPUT MODULE FOR TC 'TC1'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MODIFY TABLE
MODULE TC1_MODIFY INPUT.
  MODIFY IT_ITEM
    FROM WA_ITEM
    INDEX TC1-CURRENT_LINE.
ENDMODULE.

*&SPWIZARD: INPUT MODUL FOR TC 'TC1'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: MARK TABLE
MODULE TC1_MARK INPUT.
  DATA: G_TC1_WA2 LIKE LINE OF IT_ITEM.
  IF TC1-LINE_SEL_MODE = 1
  AND WA_ITEM-MARK = 'X'.
    LOOP AT IT_ITEM INTO G_TC1_WA2
      WHERE MARK = 'X'.
      G_TC1_WA2-MARK = ''.
      MODIFY IT_ITEM
        FROM G_TC1_WA2
        TRANSPORTING MARK.
    ENDLOOP.
  ENDIF.
  MODIFY IT_ITEM
    FROM WA_ITEM
    INDEX TC1-CURRENT_LINE
    TRANSPORTING MARK.
ENDMODULE.

*&SPWIZARD: INPUT MODULE FOR TC 'TC1'. DO NOT CHANGE THIS LINE!
*&SPWIZARD: PROCESS USER COMMAND
MODULE TC1_USER_COMMAND INPUT.
  OK_CODE = SY-UCOMM.
  PERFORM USER_OK_TC USING    'TC1'
                              'IT_ITEM'
                              'MARK'
                     CHANGING OK_CODE.
  SY-UCOMM = OK_CODE.
ENDMODULE.
*&---------------------------------------------------------------------*
*&      Module  USER_COMMAND_9000  INPUT
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
MODULE USER_COMMAND_9000 INPUT.

  OK_CODE = SY-UCOMM .
  CASE OK_CODE .
    WHEN 'SAVE'.
      PERFORM BAPI .
    WHEN 'EXIT'.
      LEAVE TO SCREEN 0 .
    WHEN 'CANCEL'.
      LEAVE TO SCREEN 0 .

    WHEN OTHERS.
  ENDCASE.
  CLEAR WA_HEADER-CADDR .
  IF WA_HEADER-SITE IS NOT INITIAL ."and WA_HEADER-CADDR is INITIAL .
    CLEAR WA_HEADER-CADDR .
    SELECT SINGLE WERKS
           ADRNR
           EKORG FROM T001W INTO WA_T001W
           WHERE WERKS = WA_HEADER-SITE.
  IF wa_t001w is NOT INITIAL .
  SELECT SINGLE ADDRNUMBER
           DATE_FROM
           NATION
           NAME1
           CITY1
           POST_CODE1
           STREET
           COUNTRY
           REGION
           STR_SUPPL1
           STR_SUPPL2 FROM ADRC INTO WA_ADRC
           WHERE ADDRNUMBER  = WA_T001W-ADRNR .

  SELECt SINGLE BWKEY
                BUKRS from t001k into wa_t001k
                WHERE BWKEY = WA_T001W-WERKS .


         SELECT SINGLE * FROM T026Z INTO WA_T026Z WHERE EKORG = WA_T001W-EKORG .
  ENDIF.








    IF WA_ADRC-STREET IS NOT INITIAL.
      WA_HEADER-CADDR = WA_ADRC-STREET.
*    CONCATENATE  WA_HEADER-vADDR WA_ADRC1-STREET  INTO WA_HEADER-VADDR SEPARATED BY ',' .
    ENDIF.
    IF WA_ADRC-CITY1 IS NOT INITIAL AND WA_HEADER-CADDR IS NOT INITIAL .
      CONCATENATE WA_HEADER-CADDR  WA_ADRC-CITY1 INTO WA_HEADER-CADDR SEPARATED BY ',' .
    ELSE .
      CONCATENATE WA_HEADER-CADDR  WA_ADRC-CITY1 INTO WA_HEADER-CADDR ."SEPARATED BY ',' .
    ENDIF.

    IF WA_ADRC-POST_CODE1 IS NOT INITIAL .
      CONCATENATE WA_HEADER-CADDR  WA_ADRC-POST_CODE1 INTO WA_HEADER-CADDR SEPARATED BY '-' .
    ENDIF.
*BREAK-POINT.

    NUM = STRLEN( WA_HEADER-CADDR ).
    NUM1 = 120 - NUM .
    NUM = NUM1 / 2 .
*    DO NUM TIMES.
*      SHIFT WA_HEADER-CADDR LEFT CIRCULAR.
*    ENDDO.
**    WRITE: / TEXT.

    SHIFT WA_HEADER-CADDR BY NUM PLACES RIGHT .

  ENDIF.
  IF WA_HEADER-LIFNR IS NOT INITIAL .
    CLEAR WA_HEADER-VADDR.
    SELECT SINGLE LIFNR
           LAND1
           NAME1
           ADRNR
           STCD3 FROM LFA1 INTO WA_LFA1
           WHERE LIFNR = WA_HEADER-LIFNR.

    SELECT SINGLE ADDRNUMBER
        DATE_FROM
        NATION
        NAME1
        CITY1
        POST_CODE1
        STREET
        COUNTRY
        REGION
        STR_SUPPL1
        STR_SUPPL2 FROM ADRC INTO WA_ADRC1
        WHERE ADDRNUMBER  = WA_LFA1-ADRNR .


    CLEAR : WA_HEADER-NAME1, WA_HEADER-STCD3 .
    WA_HEADER-NAME1 = WA_ADRC1-NAME1.
    WA_HEADER-STCD3 = WA_LFA1-STCD3.
    IF WA_ADRC1-STREET IS NOT INITIAL.
      WA_HEADER-VADDR = WA_ADRC1-STREET.
*    CONCATENATE  WA_HEADER-vADDR WA_ADRC1-STREET  INTO WA_HEADER-VADDR SEPARATED BY ',' .
    ENDIF.

    IF WA_ADRC1-CITY1 IS NOT INITIAL AND WA_HEADER-VADDR IS NOT INITIAL .
      CONCATENATE WA_HEADER-VADDR  WA_ADRC1-CITY1 INTO WA_HEADER-VADDR SEPARATED BY ',' .
    ELSE .
      CONCATENATE WA_HEADER-VADDR  WA_ADRC1-CITY1 INTO WA_HEADER-VADDR . "SEPARATED BY ',' .
    ENDIF.


    IF WA_ADRC1-POST_CODE1 IS NOT INITIAL .
      CONCATENATE WA_HEADER-VADDR  WA_ADRC1-POST_CODE1 INTO WA_HEADER-VADDR SEPARATED BY '-' .
    ENDIF.
  ENDIF.


  IF WA_HEADER-AEDAT IS NOT INITIAL AND LV_LEAD IS NOT INITIAL.

    CALL FUNCTION 'RP_CALC_DATE_IN_INTERVAL'
      EXPORTING
        DATE      = WA_HEADER-AEDAT
        DAYS      = LV_LEAD
        MONTHS    = '00'
        SIGNUM    = '+'
        YEARS     = '00'
      IMPORTING
        CALC_DATE = WA_HEADER-AEDAT1.
  ENDIF.













ENDMODULE.
