*&---------------------------------------------------------------------*
*& Include          ZSD_PICK_LIST_015_FORM
*&---------------------------------------------------------------------*
SELECT
  VBELN
  VSTEL
  KODAT
  KUNNR
  BLDAT FROM LIKP INTO TABLE IT_LIKP
  WHERE VBELN = P_VBELN.

IF IT_LIKP IS NOT INITIAL.

  SELECT
     VBELN
     POSNR
     MATNR
     LGORT
     LFIMG
     VRKME
     VGBEL
     WRF_CHARSTC2 FROM LIPS INTO TABLE IT_LIPS
     FOR ALL ENTRIES IN IT_LIKP
     WHERE VBELN = IT_LIKP-VBELN.

  SELECT
    VSTEL
    ADRNR FROM TVST INTO TABLE IT_TVST
    FOR ALL ENTRIES IN IT_LIKP
    WHERE VSTEL = IT_LIKP-VSTEL.
ENDIF.

READ TABLE IT_LIKP INTO WA_LIKP INDEX 1.
IF WA_LIKP IS NOT INITIAL.
  SELECT SINGLE
    KUNNR
    ADRNR
    LAND1 FROM KNA1 INTO WA_KNA1
    WHERE KUNNR = WA_LIKP-KUNNR.

ENDIF.

READ TABLE IT_TVST INTO WA_TVST INDEX 1.
IF WA_TVST IS NOT INITIAL.

  SELECT SINGLE
     ADDRNUMBER
     NAME1
     CITY1
     POST_CODE1
     STREET
     STR_SUPPL1
     STR_SUPPL2 FROM ADRC INTO WA_ADRC
     WHERE ADDRNUMBER = WA_TVST-ADRNR.

ENDIF.

IF WA_KNA1 IS NOT INITIAL.
  SELECT SINGLE
      ADDRNUMBER
      NAME1
      CITY1
      POST_CODE1
      STREET
      STR_SUPPL1
      STR_SUPPL2 FROM ADRC INTO WA_ADRC1
      WHERE ADDRNUMBER = WA_KNA1-ADRNR.

  SELECT SINGLE
    SPRAS
    LAND1
    LANDX FROM T005T INTO WA_T005T
    WHERE LAND1 = WA_KNA1-LAND1
    AND SPRAS   = SY-LANGU.


ENDIF.

IF IT_LIPS IS NOT INITIAL.

  SELECT
    VBELN
    BSTNK FROM VBAK INTO TABLE IT_VBAK
    FOR ALL ENTRIES IN IT_LIPS
    WHERE VBELN = IT_LIPS-VGBEL.

  SELECT
    MATNR
    MATKL
    SATNR
    COLOR_ATINN
    COLOR
    SIZE1 FROM MARA INTO TABLE IT_MARA
    FOR ALL ENTRIES IN IT_LIPS
    WHERE MATNR = IT_LIPS-MATNR.

  SELECT
    MSEHI
    FAMUNIT FROM T006 INTO TABLE IT_T006
    FOR ALL ENTRIES IN IT_LIPS
    WHERE MSEHI = IT_LIPS-VRKME.

ENDIF.
IF IT_MARA IS NOT INITIAL.

  SELECT
    ATINN
    ATWRT
    SPRAS
    ATWTB FROM WRF_CHARVALT INTO TABLE IT_WRF_CHARVALT
    FOR ALL ENTRIES IN IT_MARA
    WHERE ATINN = IT_MARA-COLOR_ATINN
    AND   ATWRT = IT_MARA-COLOR
    AND   SPRAS = SY-LANGU.





ENDIF.
READ TABLE IT_LIPS INTO WA_LIPS INDEX 1.
IF WA_LIPS IS NOT INITIAL.

  SELECT SINGLE
  RUUID
  VBELV
  POSNV
  VBELN FROM VBFA INTO WA_VBFA
  WHERE VBELN = WA_LIPS-VBELN.

ENDIF.

WA_HEADER-NAME1         = WA_ADRC-NAME1.
WA_HEADER-CITY1         = WA_ADRC-CITY1.
WA_HEADER-POST_CODE1    = WA_ADRC-POST_CODE1.
WA_HEADER-STREET        = WA_ADRC-STREET.
WA_HEADER-STR_SUPPL1    = WA_ADRC-STR_SUPPL1.
WA_HEADER-STR_SUPPL2    = WA_ADRC-STR_SUPPL2.
WA_HEADER-NAME1_SH      = WA_ADRC1-NAME1.
WA_HEADER-CITY1_SH      = WA_ADRC1-CITY1.
WA_HEADER-POST_CODE1_SH = WA_ADRC1-POST_CODE1.
WA_HEADER-STREET_SH     = WA_ADRC1-STREET.
WA_HEADER-STR_SUPPL1_SH = WA_ADRC1-STR_SUPPL1.
WA_HEADER-STR_SUPPL2_SH = WA_ADRC1-STR_SUPPL2.
WA_HEADER-VBELN         = WA_LIKP-VBELN.
WA_HEADER-BLDAT         = WA_LIKP-BLDAT.
WA_HEADER-KODAT         = WA_LIKP-KODAT.
WA_HEADER-LANDX         = WA_T005T-LANDX.
WA_HEADER-LANDX1        = WA_T005T-LANDX.
WA_HEADER-PO_NUM        = WA_VBFA-VBELV.


LOOP AT IT_LIPS INTO WA_LIPS.
  LV_1 = WA_LIPS-LFIMG.
  SPLIT LV_1 AT '.' INTO LV_2 LV_3.
  LV_CNT                = LV_CNT + 1.
  WA_FINAL-SL           = LV_CNT .
  WA_FINAL-VRKME        = WA_LIPS-VRKME.
  WA_FINAL-WRF_CHARSTC2 = WA_LIPS-WRF_CHARSTC2.
  WA_FINAL-LFIMG        = LV_2.
  LV_TOTAL              = LV_TOTAL + WA_LIPS-LFIMG.
  WA_FINAL-LGORT        = WA_LIPS-LGORT.

*  CALL FUNCTION 'READ_TEXT'
*    EXPORTING
**     CLIENT                        = SY-MANDT
*      ID                            = 'GRUN'
*      LANGUAGE                      = 'EN'
*      NAME                          = MATNR
*      OBJECT                        = 'LIPS'
**     ARCHIVE_HANDLE                = 0
**     LOCAL_CAT                     = ' '
**   IMPORTING
**     HEADER                        =
**     OLD_LINE_COUNTER              =
*    TABLES
*      LINES                         = IT_LINES
**   EXCEPTIONS
**     ID                            = 1
**     LANGUAGE                      = 2
**     NAME                          = 3
**     NOT_FOUND                     = 4
**     OBJECT                        = 5
**     REFERENCE_CHECK               = 6
**     WRONG_ACCESS_TO_ARCHIVE       = 7
**     OTHERS                        = 8
*            .
*  IF SY-SUBRC <> 0.
** Implement suitable error handling here
*  ENDIF.
*IF sy-subrc = 0.
*
*READ TABLE IT_LINES INTO WA_LINES index 1.
*
*WA_FINAL-COLOUR = wa_tlines-tdline.
*CLEAR wa_tline.
*
*ENDIF.


  READ TABLE IT_VBAK INTO WA_VBAK WITH KEY VBELN = WA_LIPS-VGBEL.
  IF SY-SUBRC = 0.
    WA_FINAL-BSTNK        = WA_VBAK-BSTNK.
  ENDIF.

  READ TABLE IT_MARA INTO WA_MARA WITH KEY MATNR = WA_LIPS-MATNR.
  IF SY-SUBRC = 0.
    WA_FINAL-SATNR = WA_MARA-SATNR.
    WA_FINAL-MATKL = WA_MARA-MATKL.
    WA_FINAL-MATNR = WA_MARA-MATNR.
    WA_FINAL-SIZE  = WA_MARA-SIZE1.
  ENDIF.

  READ TABLE IT_WRF_CHARVALT INTO WA_WRF_CHARVALT WITH KEY ATINN = WA_MARA-COLOR_ATINN
                                                           ATWRT = WA_MARA-COLOR
                                                           SPRAS = SY-LANGU.
  IF SY-SUBRC = 0.

    WA_FINAL-COLOR = WA_WRF_CHARVALT-ATWTB.

  ENDIF.

  CALL FUNCTION 'MERCHANDISE_GROUP_HIER_ART_SEL'
    EXPORTING
      MATKL       = WA_FINAL-MATKL
      SPRAS       = SY-LANGU
    TABLES
      O_WGH01     = IT_O_WGH01
    EXCEPTIONS
      NO_BASIS_MG = 1
      NO_MG_HIER  = 2
      OTHERS      = 3.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  READ TABLE IT_O_WGH01 INTO WA_O_WGH01 INDEX 1.
  IF SY-SUBRC = 0.

    WA_FINAL-HIER = WA_O_WGH01-WWGHA.
    CLEAR WA_O_WGH01.
  ENDIF.



  READ TABLE IT_T006 INTO WA_T006 WITH KEY MSEHI = WA_LIPS-VRKME.

  IF SY-SUBRC = 0.
    WA_FINAL-FAMUNIT = WA_T006-FAMUNIT.
  ENDIF.

  APPEND WA_FINAL TO IT_FINAL.
  CLEAR: WA_FINAL,WA_T006,WA_LIPS.

ENDLOOP.


CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
  EXPORTING
    FORMNAME           = 'ZSD_PICK_LISTF'
*   VARIANT            = ' '
*   DIRECT_CALL        = ' '
  IMPORTING
    FM_NAME            = FMNAME
  EXCEPTIONS
    NO_FORM            = 1
    NO_FUNCTION_MODULE = 2
    OTHERS             = 3.
IF SY-SUBRC <> 0.
* Implement suitable error handling here
ENDIF.

CALL FUNCTION FMNAME
  EXPORTING
    WA_HEADER        = WA_HEADER
    LV_TOTAL         = LV_TOTAL
    lv_vbeln         = P_VBELN
  TABLES
    IT_FINAL         = IT_FINAL
  EXCEPTIONS
    FORMATTING_ERROR = 1
    INTERNAL_ERROR   = 2
    SEND_ERROR       = 3
    USER_CANCELED    = 4
    OTHERS           = 5.
IF SY-SUBRC <> 0.
*           Implement suitable error handling here
ENDIF.
