*&---------------------------------------------------------------------*
*& Include          ZSMM_MAT_IDC_T_S01
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS : P_FILE TYPE STRING.
PARAMETERS : P_RAD1 RADIOBUTTON GROUP RB1.
PARAMETERS : P_RAD2 RADIOBUTTON GROUP RB1.
PARAMETERS : P_BG AS CHECKBOX.
SELECTION-SCREEN END OF BLOCK B1.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.
  PERFORM GET_FILENAME CHANGING P_FILE.

AT SELECTION-SCREEN.
  PERFORM SET_BACKGROUND_JOB.
