*&---------------------------------------------------------------------*
*& Include          ZSST_MM_R_APPR_PR_TOP
*&---------------------------------------------------------------------*

TYPE-POOLS: SLIS.                                 "ALV Declarations


TYPES : BEGIN OF TY_MARA,
          MATKL          TYPE MARA-MATKL,
          MATNR          TYPE MARA-MATNR,
          EAN11          TYPE MARA-EAN11,
          ZZPO_ORDER_TXT TYPE MARA-ZZPO_ORDER_TXT,
          LIFNR          TYPE A502-LIFNR,
        END OF TY_MARA,

        BEGIN OF TY_A515,
          KAPPL TYPE A515-KAPPL,
          KSCHL TYPE A515-KSCHL,
          MATNR TYPE A515-MATNR,
          KFRST TYPE A515-KFRST,
          DATBI TYPE A515-DATBI,
          KNUMH TYPE A515-KNUMH,
        END OF TY_A515,

        BEGIN OF TY_A502,
          KAPPL TYPE A502-KAPPL,
          KSCHL TYPE A502-KSCHL,
          LIFNR TYPE A502-LIFNR,
          MATNR TYPE A502-MATNR,
          KFRST TYPE A502-KFRST,
          DATBI TYPE A502-DATBI,
          KNUMH TYPE A502-KNUMH,
        END OF TY_A502,

        BEGIN OF TY_A516,
          KAPPL TYPE A516-KAPPL,
          KSCHL TYPE A516-KSCHL,
          MATNR TYPE A516-MATNR,
          EAN11 TYPE A516-EAN11,
          KFRST TYPE A516-KFRST,
          DATBI TYPE A516-DATBI,
          KNUMH TYPE A516-KNUMH,
        END OF TY_A516,

        BEGIN OF TY_KONP,
          KNUMH TYPE KONP-KNUMH,
          KOPOS TYPE KONP-KOPOS,
          KBETR TYPE KONP-KBETR,
        END OF TY_KONP,

        BEGIN OF TY_LFA1,
          LIFNR TYPE LFA1-LIFNR,
          NAME1 TYPE LFA1-NAME1,
          ORT01 TYPE LFA1-ORT01,
        END OF TY_LFA1,

        BEGIN OF TY_VENDOR,
          MATNR TYPE A502-MATNR,
          LIFNR TYPE A502-LIFNR,
        END OF TY_VENDOR,

        BEGIN OF TY_PA1,
          MATNR TYPE MARA-MATNR,
          EAN11 TYPE MARA-EAN11,
        END OF TY_PA1,

        BEGIN OF TY_DISPLAY,
          SLNO(10),
          LOCNR(10) ,
          MATKL(10) ,
          TYPE      TYPE BAPI_MTYPE,
          MESSAGE	  TYPE BAPI_MSG,
        END OF TY_DISPLAY,

        BEGIN OF TY_MBEW ,
          MATNR TYPE MBEW-MATNR ,
          BWKEY TYPE MBEW-BWKEY ,
          BWTAR TYPE MBEW-BWTAR ,
          LBKUM TYPE MBEW-LBKUM ,
          SALK3 TYPE MBEW-SALK3 ,
        END OF TY_MBEW.

DATA  : IT_MARA    TYPE TABLE OF TY_MARA,
        IT_A515    TYPE TABLE OF TY_A515,
        IT_A502    TYPE TABLE OF TY_A502,
        IT_A516    TYPE TABLE OF TY_A516,
        IT_MRP     TYPE TABLE OF TY_KONP,
        IT_502     TYPE TABLE OF TY_KONP,
        IT_516     TYPE TABLE OF TY_KONP,
        IT_LFA1    TYPE TABLE OF TY_LFA1,
        IT_FINAL   TYPE TABLE OF ZAFPC_ST,
        IT_FIN     TYPE TABLE OF ZAF_PC WITH HEADER LINE,
        IT_FIN1    TYPE TABLE OF ZAF_PC,
        IT_TAB     TYPE TABLE OF ZAF_PC,
        IT_DISPLAY TYPE TABLE OF TY_DISPLAY,
        IT_PA1     TYPE TABLE OF TY_PA1,
        IT_VENDOR  TYPE TABLE OF TY_VENDOR,
        IT_MBEW    TYPE TABLE OF TY_MBEW.

DATA: FIELDCATALOG TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
      LS_FIELDCAT  TYPE LVC_S_FCAT,
      I_HEADING    TYPE SLIS_T_LISTHEADER,
      WA_HEADING   LIKE LINE OF I_HEADING,
      I_EVENTS     TYPE SLIS_T_EVENT.


DATA  : WA_MARA    TYPE TY_MARA,
        WA_A515    TYPE TY_A515,
        WA_A502    TYPE TY_A502,
        WA_A516    TYPE TY_A516,
        WA_MRP     TYPE TY_KONP,
        WA_502     TYPE TY_KONP,
        WA_516     TYPE TY_KONP,
        WA_LFA1    TYPE TY_LFA1,
        WA_FINAL   TYPE ZAFPC_ST,
        WA_HDR     TYPE ZINW_T_HDR,
        WA_EVENTS  LIKE LINE OF I_EVENTS,
        WA_TAB     LIKE LINE OF IT_TAB,
        WA_FIN     TYPE ZAF_PC,
        WA_FIN1    TYPE ZAF_PC,
        WA_DISPLAY TYPE TY_DISPLAY,
        WA_PA1     TYPE TY_PA1,
        WA_VENDOR  TYPE TY_VENDOR,
        WA_MBEW    TYPE TY_MBEW.

DATA  : LV_GROUP_ID TYPE MARA-MATKL,
        LV_IMDOC    TYPE CHAR20,
        LV_CRD_MM   TYPE CHAR10.

DATA  : FM_NAME  TYPE RS38L_FNAM .

DATA  : V_LEN_IN LIKE SOOD-OBJLEN,
        GD_UCOMM TYPE SY-UCOMM,
        FLAG     TYPE C,
        SR_NO    TYPE INT2,
        DATE     TYPE CHAR10,
        CAL_AMT  TYPE KONP-KBETR.

DATA: I_OTF     TYPE ITCOO    OCCURS 0 WITH HEADER LINE,
      I_TLINE   LIKE TLINE    OCCURS 0 WITH HEADER LINE,
      I_RECORD  LIKE SOLISTI1 OCCURS 0 WITH HEADER LINE,
      I_XSTRING TYPE XSTRING.

DATA:IT_MESSTAB TYPE TABLE OF BDCMSGCOLL,
     WA_MESSTAB TYPE BDCMSGCOLL.

DATA: CTUMODE LIKE CTU_PARAMS-DISMODE VALUE 'N',
      CUPDATE LIKE CTU_PARAMS-UPDMODE VALUE 'A'.

DATA: IT_BDCDATA TYPE TABLE OF BDCDATA,
      WA_BDCDATA TYPE BDCDATA.

DATA:   BDCDATA LIKE BDCDATA    OCCURS 0 WITH HEADER LINE.

DATA : VENDOR_HDR LIKE BAPIACHE09,
       VENDOR_CURR LIKE BAPIACCR09 OCCURS 0 WITH HEADER LINE,
       ACC_PAY LIKE BAPIACAP09 OCCURS 0 WITH HEADER LINE,
       IT_RETURN TYPE TABLE OF BAPIRET2 ,"OCCURS 0 WITH HEADER LINE,
       WA_RETURN TYPE BAPIRET2,
       ACC_GL LIKE BAPIACGL09 OCCURS 0 WITH HEADER LINE.
