*&---------------------------------------------------------------------*
*& Include ZSST_DEBITNOTE_TOP                       - Module Pool      ZSST_DEBITNOTE
*&---------------------------------------------------------------------*
PROGRAM ZSST_DEBITNOTE.
TYPES: BEGIN OF TY_LFA1,
*       MANDT TYPE TY_LFA1-MANDT,
         LIFNR TYPE LFA1-LIFNR,
         NAME1 TYPE LFA1-NAME1,   "VENDOR NAME
       END OF TY_LFA1,

       BEGIN OF TY_MSEG,
         MBLNR TYPE MSEG-MBLNR,    "MATERIAl DOCUMENT
         MJAHR TYPE MSEG-MJAHR,
         ZEILE TYPE MSEG-ZEILE,
         CHARG TYPE MSEG-CHARG,     "BATCH
         MATNR TYPE MSEG-MATNR,
         BWART TYPE MSEG-BWART,
         EBELN TYPE MSEG-EBELN,
       END OF TY_MSEG,

       BEGIN OF TY_EKKO,
*         MANDT TYPE EKKO-MANDT,
         EBELN TYPE EKKO-EBELN,     "PO#
         KNUMV TYPE EKKO-KNUMV,
         LIFNR TYPE EKKO-LIFNR,
         WAERS TYPE EKKO-WAERS,
       END OF TY_EKKO,

       BEGIN OF TY_EKPO,
         EBELN TYPE EKPO-EBELN,
         EBELP TYPE EKPO-EBELP,
         MATNR TYPE EKPO-MATNR,     "SST CODE
         MEINS TYPE EKPO-MEINS,     "unit
         MENGE TYPE EKPO-MENGE,     "qty
         NETPR TYPE EKPO-NETPR,     "AMOUNT
       END OF TY_EKPO,

       BEGIN OF TY_PRCD_ELEMENTS,
         KNUMV TYPE PRCD_ELEMENTS-KNUMV,
         KPOSN TYPE PRCD_ELEMENTS-KPOSN,
         STUNR TYPE PRCD_ELEMENTS-STUNR,
         ZAEHK TYPE PRCD_ELEMENTS-ZAEHK,
         KBETR TYPE PRCD_ELEMENTS-KBETR,    "gst%
         KWERT TYPE PRCD_ELEMENTS-KWERT,    "GST
         WAERS TYPE PRCD_ELEMENTS-WAERS,
       END OF TY_PRCD_ELEMENTS,

       BEGIN OF TY_ZINW_T_ITEM,
         QR_CODE TYPE ZINW_T_ITEM-QR_CODE,
         EBELN   TYPE ZINW_T_ITEM-EBELN,
         EBELP   TYPE ZINW_T_ITEM-EBELP,
         SNO     TYPE ZINW_T_ITEM-SNO,
         MATNR   TYPE ZINW_T_ITEM-MATNR,
       END OF TY_ZINW_T_ITEM.

TYPES: BEGIN OF TY_HDR,
         EBELN   TYPE EBELN,
         QR_CODE TYPE ZQR_CODE,
       END OF TY_HDR.

TYPES: BEGIN OF TY_DET,
         EBELN       TYPE EBELN,
         MBLNR       TYPE MBLNR,
         MJAHR       TYPE MJAHR,
         MSG_TYPE(1),
         MESSAGE     TYPE BAPIRET2-MESSAGE,
       END OF TY_DET.

TYPES: BEGIN OF TY_ITEM,
         QR_CODE TYPE    ZQR_CODE,
         EBELN   TYPE    EBELN,
         EBELP   TYPE    EBELP,
         MATNR   TYPE    MATNR,
         LGORT   TYPE    LGORT_D,
         WERKS   TYPE    EWERK,
         MAKTX   TYPE    MAKTX,
         MATKL   TYPE    MATKL,
         MENGE_P TYPE    ZMENGE_P,
         MEINS   TYPE    BSTME,
       END OF TY_ITEM.

DATA: IT_LFA1          TYPE TABLE OF TY_LFA1,
      WA_LFA1          TYPE  TY_LFA1,
      IT_MSEG          TYPE TABLE OF TY_MSEG,
      WA_MSEG          TYPE  TY_MSEG,
      IT_EKKO          TYPE TABLE OF TY_EKKO,
      WA_EKKO          TYPE  TY_EKKO,
      IT_EKPO          TYPE TABLE OF TY_EKPO,
      WA_EKPO          TYPE  TY_EKPO,
      IT_ITEM_1        TYPE TABLE OF ZDEBIT_NOTE,
      WA_ITEM_1        TYPE ZDEBIT_NOTE,
      IT_PRCD_ELEMENTS TYPE TABLE OF TY_PRCD_ELEMENTS,
      WA_PRCD_ELEMENTS TYPE TY_PRCD_ELEMENTS,
      IT_ZINW_T_ITEM   TYPE TABLE OF TY_ZINW_T_ITEM,
      WA_ZINW_T_ITEM   TYPE TY_ZINW_T_ITEM,
      WA_HEADER        TYPE ZSST_HEADER,
      LV_LIFNR         TYPE LFA1-LIFNR,
      LV_BATCH         TYPE MSEG-CHARG,
      LV_QR_CODE       TYPE ZQR_CODE,
      LV_MBLNR         TYPE MSEG-MBLNR,
      LV_MATNR         TYPE MSEG-MATNR,
*      LV_AMOUNT        TYPE BPREI,
      SLNO             TYPE I,
      LV_GST%          TYPE KBETR_KOND.


CONTROLS TAB1 TYPE TABLEVIEW USING SCREEN 9000.
DATA: LT_HDR  TYPE STANDARD TABLE OF TY_HDR,
      LT_ITEM TYPE STANDARD TABLE OF TY_ITEM,
      LT_DET  TYPE STANDARD TABLE OF TY_DET.

*** Work area Declarations
DATA: WA_ITEM TYPE TY_ITEM,
      WA_DET  TYPE TY_DET.

*** BAPI Structure Declaration
DATA:
  WA_GMVT_HEADER  TYPE BAPI2017_GM_HEAD_01,
  WA_GMVT_ITEM    TYPE BAPI2017_GM_ITEM_CREATE,
  WA_GMVT_HEADRET TYPE BAPI2017_GM_HEAD_RET,
  LT_BAPIRET      TYPE STANDARD TABLE OF BAPIRET2,
  LT_GMVT_ITEM    TYPE STANDARD TABLE OF BAPI2017_GM_ITEM_CREATE.
FIELD-SYMBOLS :
  <LS_BAPIRET> TYPE BAPIRET2.
