*&---------------------------------------------------------------------*
*& Include          ZTP3_PRINTS_P01
*&---------------------------------------------------------------------*
START-OF-SELECTION.
  IF P_QR IS INITIAL.
    MESSAGE S006(ZMSG_CLS) DISPLAY LIKE 'E'.
    LEAVE LIST-PROCESSING.
  ELSE.
    SELECT SINGLE * FROM ZINW_T_HDR INTO LS_HDR WHERE QR_CODE = P_QR AND STATUS GE '03'.
    IF LS_HDR IS INITIAL.
      MESSAGE S003(ZMSG_CLS) DISPLAY LIKE 'E'.
    ENDIF.
  ENDIF.

*** Print Control
*  IF P_QR IS NOT INITIAL AND R_LABLES IS NOT INITIAL.
*    PERFORM PRINT_LABELS.
*  ELSEIF P_QR IS NOT INITIAL AND R_GRPO_P IS NOT INITIAL.
*    PERFORM PRINT_GRPO_P.
*  ELSEIF P_QR IS NOT INITIAL AND R_GRPO_S IS NOT INITIAL.
*    PERFORM PRINT_GRPO_S.
*  ENDIF.

  CHECK P_QR IS NOT INITIAL.
    PERFORM PRINT_LABELS.
