*&---------------------------------------------------------------------*
*& Include          ZXM06U37
*&---------------------------------------------------------------------*

*CI_EKKODB-AGENT_NAME
*CI_EKKODB-USER_NAME
*CI_EKKODB-ERDATE
*CI_EKKODB-APPROVER1
*CI_EKKODB-APPROVER1_DT
*CI_EKKODB-APPROVER2
*CI_EKKODB-APPROVER2_DT
*BREAK PREDDY.
*IF SY-TCODE = 'ME21N' OR SY-TCODE = 'ME22N' OR SY-TCODE = 'ME23N' .


  E_CI_EKKO-AGENT_NAME   = EKKO_CI-AGENT_NAME.
  E_CI_EKKO-USER_NAME    = EKKO_CI-USER_NAME.
  E_CI_EKKO-ERDATE       = EKKO_CI-ERDATE.
  E_CI_EKKO-APPROVER1    = EKKO_CI-APPROVER1.
  E_CI_EKKO-APPROVER1_DT = EKKO_CI-APPROVER1_DT.
  E_CI_EKKO-APPROVER2    = EKKO_CI-APPROVER2.
  E_CI_EKKO-APPROVER2_DT = EKKO_CI-APPROVER2_DT.
  E_CI_EKKO-ZDAYS = EKKO_CI-ZDAYS.

*ENDIF.
